[package]
name = "sanctions-engine-rs"
version = "2.0.0"
edition = "2021"
[[bin]]
name = "sanctions-engine-rs"
path = "src/main.rs"
[dependencies]
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
