replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54link-dev-interest-rate-engine-go
  pullPolicy: IfNotPresent
  tag: "0.0.1"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54link
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9373
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    ephemeral-storage: 1Gi
    cpu: 300m
    memory: 512Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: interest-rate-engine-go
  appPort: 9373
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  DATABASE_URL: "postgresql://doadmin:AVNS_MSy6CW3EGXnA8wJgkLv@db-postgresql-nyc1-18193-do-user-10555812-0.e.db.ondigitalocean.com:25060/link_core_banking?sslmode=require"
  DATABASE_URI: "postgresql://doadmin:AVNS_MSy6CW3EGXnA8wJgkLv@db-postgresql-nyc1-18193-do-user-10555812-0.e.db.ondigitalocean.com:25060/link_core_banking?sslmode=require"
  DATABASE_POOL_SIZE: "3"
  DB_HOST: db-postgresql-nyc1-18193-do-user-10555812-0.e.db.ondigitalocean.com
  DB_PORT: "25060"
  DB_NAME: link_core_banking
  DB_USER: doadmin
  DB_PASSWORD: AVNS_MSy6CW3EGXnA8wJgkLv
  REDIS_URL: redis-master.redis.svc.cluster.local:6379
  REDIS_ADDRESS: redis-master.redis.svc.cluster.local:6379
  REDIS_HOST: redis-master.redis.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_PASSWORD: 3phHSv7qbAuZLb2pi9FWED2X
  KAFKA_BROKERS: mojaloop-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  KAFKA_BOOTSTRAP_SERVERS: mojaloop-kafka-cluster-kafka-bootstrap.kafka.svc:9092
  KAFKA_SECURITY_PROTOCOL: PLAINTEXT
  KAFKA_SASL_MECHANISM: ""
  KAFKA_SASL_USERNAME: ""
  KAFKA_SASL_PASSWORD: ""
  KEYCLOAK_URL: https://keycloak.servers.upi.dev
  KEYCLOAK_BASE_URL: https://keycloak.servers.upi.dev
  KEYCLOAK_ADMIN_USERNAME: admin
  KEYCLOAK_ADMIN_PASSWORD: "0lQ09=4+Wcpi)DW"
  DEFAULT_KEYCLOAK_REALM: 54link
  AUTH_ENFORCER_URL: "http://auth-enforcer-rs.54link-dev.svc.cluster.local:8314"
  ALLOWED_ORIGINS: "*"
  PERMIFY_URL: http://permify.permify.svc.cluster.local:3476
  PERMIFY_HOST: permify.54link-dev.svc.cluster.local
  PERMIFY_PORT: "3476"
  DAPR_URL: "http://localhost:3500"
  DAPR_HTTP_PORT: "3500"
  DAPR_PUBSUB: pubsub
  DAPR_PUBSUB_NAME: pubsub
  DAPR_PLACEMENT_ADDRESS: dapr-placement:50005
  TEMPORAL_ADDRESS: temporal-frontend.temporal.svc:7233
  TEMPORAL_NAMESPACE: "54link-dev"
  APISIX_ADMIN_URL: http://apisix-admin.apisix.svc.cluster.local:9180
  OPENSEARCH_URL: https://shared-cluster-master.opensearch.svc.cluster.local:9200
  OPENSEARCH_USERNAME: admin
  OPENSEARCH_PASSWORD: "newwave@opensearch"
  OPENSEARCH_VERIFY_CERTS: "false"
  APP_HOST: "0.0.0.0"
  APP_PORT: "9373"
  PORT: "9373"
  PORT_BASE: "9373"
  LOG_LEVEL: info
  SERVICE_GROUP: interest-rate-engine-go
  SERVICES: "interest-rate-engine-go"
