replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54link-dev-verification-ui
  pullPolicy: IfNotPresent
  tag: "0.0.3"
nameOverride: ""
fullnameOverride: "verification-ui"
serviceAccount:
  create: false
  name: 54link
podAnnotations: {}
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    ephemeral-storage: 512Mi
    cpu: 200m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
