replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54link-dev-channels-mobile-web
  pullPolicy: IfNotPresent
  tag: "0.0.1"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54link
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9169
    - port: 9170
    - port: 9171
    - port: 9172
    - port: 9173
    - port: 9174
    - port: 9175
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    ephemeral-storage: 2Gi
    cpu: 500m
    memory: 1Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: channels-mobile-web
  appPort: 9169
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  APP_PORT: "9169"
  PORT_BASE: "9169"
  SERVICE_GROUP: channels-mobile-web
  SERVICES: "custom-domain-go,developer-platform-service,developer-portal-go,mobile-bff,open-banking-baas-go,open-banking-go,stk-service"
