-- Rollback: 001_create_insurance_portfolio_analytics_tables
BEGIN;
DROP TRIGGER IF EXISTS trg_insurance_portfolio_analytics_updated ON insurance_portfolio_analytics_records;
DROP FUNCTION IF EXISTS update_insurance_portfolio_analytics_timestamp();
DROP FUNCTION IF EXISTS cleanup_insurance_portfolio_analytics_idempotency();
DROP POLICY IF EXISTS insurance_portfolio_analytics_tenant_isolation ON insurance_portfolio_analytics_records;
DROP TABLE IF EXISTS insurance_portfolio_analytics_idempotency;
DROP TABLE IF EXISTS insurance_portfolio_analytics_audit;
DROP TABLE IF EXISTS insurance_portfolio_analytics_records;
COMMIT;
