import type { Express } from "express";

/**
 * Agriculture Enhancement — 40 services (ports 8589–8628)
 */

interface AgriService { path: string; port: number; topic: string; name: string; }

const AGRI_SERVICES: AgriService[] = [
  { path: "cooperative-management", port: 8589, topic: "cooperative_management", name: "cooperative-management-go" },
  { path: "livestock-management", port: 8590, topic: "livestock_management", name: "livestock-management-rs" },
  { path: "agri-input-marketplace", port: 8591, topic: "agri_input_marketplace", name: "agri-input-marketplace-go" },
  { path: "nirsal-credit-guarantee", port: 8592, topic: "nirsal_credit_guarantee", name: "nirsal-credit-guarantee-go" },
  { path: "cbn-anchor-borrowers", port: 8593, topic: "cbn_anchor_borrowers", name: "cbn-anchor-borrowers-go" },
  { path: "interactive-ussd-agri", port: 8594, topic: "interactive_ussd_agri", name: "interactive-ussd-agri-py" },
  { path: "agri-savings-cycles", port: 8595, topic: "agri_savings_cycles", name: "agri-savings-cycles-go" },
  { path: "livestock-finance", port: 8596, topic: "livestock_finance", name: "livestock-finance-rs" },
  { path: "commodity-exchange", port: 8597, topic: "commodity_exchange", name: "commodity-exchange-rs" },
  { path: "agri-evoucher", port: 8598, topic: "agri_evoucher", name: "agri-evoucher-go" },
  { path: "commodity-price-intelligence", port: 8599, topic: "commodity_price_intelligence", name: "commodity-price-intelligence-py" },
  { path: "satellite-crop-monitor", port: 8600, topic: "satellite_crop_monitor", name: "satellite-crop-monitor-rs" },
  { path: "cooperative-credit-scoring", port: 8601, topic: "cooperative_credit_scoring", name: "cooperative-credit-scoring-py" },
  { path: "fisheries-aquaculture", port: 8602, topic: "fisheries_aquaculture", name: "fisheries-aquaculture-go" },
  { path: "farm-boundary-mapping", port: 8603, topic: "farm_boundary_mapping", name: "farm-boundary-mapping-rs" },
  { path: "area-yield-index-insurance", port: 8604, topic: "area_yield_index_insurance", name: "area-yield-index-insurance-py" },
  { path: "warehouse-management", port: 8605, topic: "warehouse_management", name: "warehouse-management-go" },
  { path: "agent-farmer-onboarding", port: 8606, topic: "agent_farmer_onboarding", name: "agent-farmer-onboarding-go" },
  { path: "livestock-insurance", port: 8607, topic: "livestock_insurance", name: "livestock-insurance-rs" },
  { path: "equipment-leasing", port: 8608, topic: "equipment_leasing", name: "equipment-leasing-go" },
  { path: "crop-yield-prediction", port: 8609, topic: "crop_yield_prediction", name: "crop-yield-prediction-py" },
  { path: "multi-peril-crop-insurance", port: 8610, topic: "multi_peril_crop_insurance", name: "multi-peril-crop-insurance-rs" },
  { path: "agri-logistics", port: 8611, topic: "agri_logistics", name: "agri-logistics-go" },
  { path: "cbn-agri-returns", port: 8612, topic: "cbn_agri_returns", name: "cbn-agri-returns-py" },
  { path: "animal-id-traceability", port: 8613, topic: "animal_id_traceability", name: "animal-id-traceability-rs" },
  { path: "nirsal-agro-geocoop", port: 8614, topic: "nirsal_agro_geocoop", name: "nirsal-agro-geocoop-go" },
  { path: "agri-iot-sensor", port: 8615, topic: "agri_iot_sensor", name: "agri-iot-sensor-rs" },
  { path: "agri-reinsurance", port: 8616, topic: "agri_reinsurance", name: "agri-reinsurance-go" },
  { path: "quality-certification", port: 8617, topic: "quality_certification", name: "quality-certification-go" },
  { path: "agri-esg-impact", port: 8618, topic: "agri_esg_impact", name: "agri-esg-impact-py" },
  { path: "crossborder-agri-trade", port: 8619, topic: "crossborder_agri_trade", name: "crossborder-agri-trade-rs" },
  { path: "cooperative-meetings", port: 8620, topic: "cooperative_meetings", name: "cooperative-meetings-go" },
  { path: "cooperative-financials", port: 8621, topic: "cooperative_financials", name: "cooperative-financials-py" },
  { path: "soil-analysis", port: 8622, topic: "soil_analysis", name: "soil-analysis-py" },
  { path: "insurance-portfolio-analytics", port: 8623, topic: "insurance_portfolio_analytics", name: "insurance-portfolio-analytics-py" },
  { path: "parametric-insurance-iot", port: 8624, topic: "parametric_insurance_iot", name: "parametric-insurance-iot-rs" },
  { path: "post-harvest-loss-tracker", port: 8625, topic: "post_harvest_loss_tracker", name: "post-harvest-loss-tracker-go" },
  { path: "aggregation-center", port: 8626, topic: "aggregation_center", name: "aggregation-center-go" },
  { path: "cbn-agsmeis", port: 8627, topic: "cbn_agsmeis", name: "cbn-agsmeis-go" },
  { path: "acgsf-guarantee", port: 8628, topic: "acgsf_guarantee", name: "acgsf-guarantee-go" },
];

const SEED_DATA: Record<string, unknown[]> = {
  cooperative_management: [{"id":"COOP-001","name":"Kano Groundnut Farmers Cooperative","coopType":"crop","state":"Kano","lga":"Fagge","memberCount":245,"repaymentRate":"94%","status":"active","registrationDate":"2024-06-15","chairperson":"Musa Abdullahi"},{"id":"COOP-002","name":"Ogun Cassava Processors Union","coopType":"processing","state":"Ogun","lga":"Abeokuta South","memberCount":180,"repaymentRate":"91%","status":"active","registrationDate":"2024-03-22","chairperson":"Bola Adeyemi"},{"id":"COOP-003","name":"Benue Rice Growers Association","coopType":"crop","state":"Benue","lga":"Makurdi","memberCount":320,"repaymentRate":"88%","status":"active","registrationDate":"2024-01-10","chairperson":"Simon Terkimbi"},{"id":"COOP-004","name":"Kaduna Tomato Farmers Cluster","coopType":"crop","state":"Kaduna","lga":"Zaria","memberCount":156,"repaymentRate":"86%","status":"active","registrationDate":"2024-09-05","chairperson":"Ibrahim Sani"},{"id":"COOP-005","name":"Enugu Palm Oil Producers","coopType":"processing","state":"Enugu","lga":"Nsukka","memberCount":98,"repaymentRate":"92%","status":"forming","registrationDate":"2025-11-20","chairperson":"Chinedu Okafor"}],
  livestock_management: [{"id":"LST-001","name":"Adamawa Cattle Ranch","category":"cattle","headCount":1250,"breed":"White Fulani","location":"Yola","owner":"Alhaji Bello Modibbo","status":"active","lastVaccination":"2026-04-15","value":"\u20a6625M"},{"id":"LST-002","name":"Oyo Poultry Farm","category":"poultry","headCount":25000,"breed":"Broiler/Layer","location":"Ibadan","owner":"Mrs. Funke Adebayo","status":"active","lastVaccination":"2026-05-01","value":"\u20a687.5M"},{"id":"LST-003","name":"Sokoto Goat Enterprise","category":"goat","headCount":800,"breed":"Red Sokoto","location":"Sokoto","owner":"Mallam Usman Danfodio","status":"active","lastVaccination":"2026-03-28","value":"\u20a6120M"},{"id":"LST-004","name":"Plateau Pig Farm","category":"pig","headCount":450,"breed":"Large White","location":"Jos","owner":"Mr. Danladi Gyang","status":"active","lastVaccination":"2026-04-20","value":"\u20a667.5M"},{"id":"LST-005","name":"Kebbi Fish Farm","category":"fish","headCount":15000,"breed":"Catfish/Tilapia","location":"Birnin Kebbi","owner":"Hajiya Amina Kebbi","status":"active","lastVaccination":"N/A","value":"\u20a645M"}],
  agri_input_marketplace: [{"id":"INP-001","name":"NPK 20:10:10 Fertilizer","category":"fertilizer","supplier":"Notore Chemical","price":"\u20a618,500/50kg","stock":"45,000 bags","region":"nationwide","status":"available","subsidyEligible":true},{"id":"INP-002","name":"Maize Hybrid Seed (SAMMAZ-15)","category":"seed","supplier":"Premier Seeds Nigeria","price":"\u20a612,000/10kg","stock":"8,200 bags","region":"North Central","status":"available","subsidyEligible":true},{"id":"INP-003","name":"Glyphosate Herbicide","category":"herbicide","supplier":"Syngenta Nigeria","price":"\u20a68,500/litre","stock":"12,000 litres","region":"nationwide","status":"available","subsidyEligible":false},{"id":"INP-004","name":"Knapsack Sprayer (16L)","category":"equipment","supplier":"Agro Allied","price":"\u20a625,000/unit","stock":"3,400 units","region":"nationwide","status":"available","subsidyEligible":false},{"id":"INP-005","name":"Rice Paddy Seed (FARO-44)","category":"seed","supplier":"NCRI Badeggi","price":"\u20a615,000/25kg","stock":"6,800 bags","region":"North Central","status":"low_stock","subsidyEligible":true}],
  nirsal_credit_guarantee: [{"id":"CRG-001","name":"Kano Wheat Expansion \u2014 Phase 2","category":"crop","guaranteeAmount":"\u20a6450M","coverage":"75%","loanAmount":"\u20a6600M","pfi":"First Bank","status":"approved","farmer":"Kano Wheat Cooperative","expiryDate":"2027-03-15"},{"id":"CRG-002","name":"Ogun Cassava Processing Plant","category":"processing","guaranteeAmount":"\u20a6225M","coverage":"50%","loanAmount":"\u20a6450M","pfi":"GTBank","status":"active","farmer":"Ogun Cassava Union","expiryDate":"2027-06-30"},{"id":"CRG-003","name":"Benue Rice Mill Finance","category":"processing","guaranteeAmount":"\u20a6180M","coverage":"75%","loanAmount":"\u20a6240M","pfi":"Zenith Bank","status":"approved","farmer":"Benue Rice Association","expiryDate":"2027-09-15"},{"id":"CRG-004","name":"Plateau Potato Storage","category":"storage","guaranteeAmount":"\u20a690M","coverage":"50%","loanAmount":"\u20a6180M","pfi":"Access Bank","status":"pending","farmer":"Plateau Potato Growers","expiryDate":"2028-01-31"}],
  cbn_anchor_borrowers: [{"id":"ABP-001","name":"Kebbi Rice Project \u2014 Dry Season 2026","category":"rice","anchor":"Labana Rice Mills","pfi":"UBA","amount":"\u20a62.4B","beneficiaries":12000,"repaymentRate":"82%","status":"disbursed","season":"dry_2026"},{"id":"ABP-002","name":"Kano Wheat Programme","category":"wheat","anchor":"Flour Mills Nigeria","pfi":"First Bank","amount":"\u20a61.8B","beneficiaries":8500,"repaymentRate":"78%","status":"repaying","season":"wet_2025"},{"id":"ABP-003","name":"Benue Soybean Cluster","category":"soybean","anchor":"TGI Group","pfi":"Zenith Bank","amount":"\u20a6900M","beneficiaries":4200,"repaymentRate":"85%","status":"disbursed","season":"wet_2026"},{"id":"ABP-004","name":"Cross River Cocoa Rehabilitation","category":"cocoa","anchor":"Olam Nigeria","pfi":"GTBank","amount":"\u20a61.2B","beneficiaries":6000,"repaymentRate":"88%","status":"active","season":"annual_2026"}],
  interactive_ussd_agri: [{"id":"USSD-AG-001","name":"*737*99# Farmer Services","category":"USSD","description":"Main agri USSD menu \u2014 EN/HA/YO/IG","status":"active","dailySessions":"45,000","languages":"4"},{"id":"USSD-AG-002","name":"*737*99*1# Crop Prices","category":"USSD","description":"Live commodity prices \u2014 maize, rice, sorghum, cassava","status":"active","dailySessions":"18,000","languages":"4"},{"id":"USSD-AG-003","name":"*737*99*2# Weather","category":"USSD","description":"5-day weather forecast for farmer's LGA","status":"active","dailySessions":"12,000","languages":"4"},{"id":"USSD-AG-004","name":"*737*99*3# Loan Status","category":"USSD","description":"Check agri-loan application and repayment status","status":"active","dailySessions":"8,500","languages":"4"}],
  agri_savings_cycles: [{"id":"VSL-001","name":"Katsina Women Thrift Group","category":"VSLA","memberCount":25,"weeklyContribution":"\u20a62,000","totalSaved":"\u20a63.2M","cycle":"Week 32/52","status":"active","shareOutDate":"2026-12-15"},{"id":"VSL-002","name":"Nasarawa Youth Farmers ROSCA","category":"ROSCA","memberCount":15,"weeklyContribution":"\u20a65,000","totalSaved":"\u20a61.8M","cycle":"Round 8/15","status":"active","shareOutDate":"2026-09-20"},{"id":"VSL-003","name":"Taraba Grain Traders Circle","category":"VSLA","memberCount":30,"weeklyContribution":"\u20a63,000","totalSaved":"\u20a64.5M","cycle":"Week 25/52","status":"active","shareOutDate":"2026-12-30"},{"id":"VSL-004","name":"Ebonyi Rice Women Group","category":"VSLA","memberCount":20,"weeklyContribution":"\u20a61,500","totalSaved":"\u20a61.1M","cycle":"Week 18/52","status":"active","shareOutDate":"2027-01-15"}],
  livestock_finance: [{"id":"LF-001","name":"Cattle Fattening Loan \u2014 Adamawa","category":"fattening","amount":"\u20a615M","tenure":"6 months","rate":"9%","collateral":"200 cattle","status":"disbursed","borrower":"Modibbo Livestock Ltd"},{"id":"LF-002","name":"Poultry Layer House \u2014 Oyo","category":"layer","amount":"\u20a68.5M","tenure":"12 months","rate":"12%","collateral":"Equipment + birds","status":"repaying","borrower":"Funke Farms Ltd"},{"id":"LF-003","name":"Goat Breeding Programme \u2014 Sokoto","category":"breeding","amount":"\u20a64.2M","tenure":"18 months","rate":"9%","collateral":"500 goats + CRG","status":"active","borrower":"Danfodio Goat Enterprise"},{"id":"LF-004","name":"Fish Pond Construction \u2014 Kebbi","category":"aquaculture","amount":"\u20a612M","tenure":"24 months","rate":"11%","collateral":"Land + equipment","status":"approved","borrower":"Kebbi Aqua Farms"}],
  commodity_exchange: [{"id":"NCX-001","name":"Maize \u2014 Lagos Spot","category":"grain","exchange":"NCX","price":"\u20a6425,000/MT","change":"+2.3%","volume":"12,400 MT","status":"trading","lastUpdate":"2026-05-14 10:30"},{"id":"NCX-002","name":"Sorghum \u2014 Kano Spot","category":"grain","exchange":"NCX","price":"\u20a6380,000/MT","change":"-1.1%","volume":"8,200 MT","status":"trading","lastUpdate":"2026-05-14 10:30"},{"id":"NCX-003","name":"Paddy Rice \u2014 AFEX","category":"grain","exchange":"AFEX","price":"\u20a6520,000/MT","change":"+0.8%","volume":"15,600 MT","status":"trading","lastUpdate":"2026-05-14 10:30"},{"id":"NCX-004","name":"Cocoa \u2014 SABEX","category":"cash_crop","exchange":"SABEX","price":"\u20a64,200,000/MT","change":"+5.2%","volume":"2,100 MT","status":"trading","lastUpdate":"2026-05-14 10:30"},{"id":"NCX-005","name":"Sesame \u2014 NCX","category":"oilseed","exchange":"NCX","price":"\u20a61,850,000/MT","change":"+1.5%","volume":"3,800 MT","status":"trading","lastUpdate":"2026-05-14 10:30"}],
  agri_evoucher: [{"id":"EVC-001","name":"NIRSAL Input Voucher \u2014 Kano","category":"fertilizer","amount":"\u20a645,000","beneficiary":"Musa Abdullahi","programme":"NIRSAL-2026","redeemed":false,"status":"active","expiryDate":"2026-09-30"},{"id":"EVC-002","name":"State Seed Subsidy \u2014 Benue","category":"seed","amount":"\u20a625,000","beneficiary":"Simon Terkimbi","programme":"Benue-Agri-2026","redeemed":true,"status":"redeemed","expiryDate":"2026-08-15"},{"id":"EVC-003","name":"CBN ABP Input Credit \u2014 Kebbi","category":"mixed","amount":"\u20a6120,000","beneficiary":"Amina Kebbi","programme":"ABP-Rice-2026","redeemed":false,"status":"active","expiryDate":"2026-10-31"},{"id":"EVC-004","name":"Herbicide Voucher \u2014 Ogun","category":"herbicide","amount":"\u20a618,000","beneficiary":"Bola Adeyemi","programme":"Ogun-Cassava-2026","redeemed":true,"status":"redeemed","expiryDate":"2026-07-30"}],
  commodity_price_intelligence: [{"id":"CPI-001","name":"Maize Price Index \u2014 North Central","category":"index","currentPrice":"\u20a6425,000/MT","weekChange":"+2.3%","monthChange":"+8.1%","forecast":"bullish","source":"NCX/AFEX","status":"active"},{"id":"CPI-002","name":"Rice Price Index \u2014 Nationwide","category":"index","currentPrice":"\u20a6520,000/MT","weekChange":"+0.8%","monthChange":"+4.5%","forecast":"stable","source":"NCX/AFEX","status":"active"},{"id":"CPI-003","name":"Cassava Price Index \u2014 South West","category":"index","currentPrice":"\u20a6180,000/MT","weekChange":"-1.2%","monthChange":"+2.1%","forecast":"stable","source":"Regional markets","status":"active"},{"id":"CPI-004","name":"Soybean Price Index \u2014 North East","category":"index","currentPrice":"\u20a6650,000/MT","weekChange":"+3.1%","monthChange":"+12.4%","forecast":"bullish","source":"NCX","status":"active"}],
  satellite_crop_monitor: [{"id":"SAT-001","name":"Kano Wheat Belt \u2014 NDVI","category":"vegetation","ndvi":"0.72","healthStatus":"good","coverage":"125,000 ha","satellite":"Sentinel-2","lastCapture":"2026-05-13","status":"active"},{"id":"SAT-002","name":"Benue Rice Fields \u2014 NDVI","category":"vegetation","ndvi":"0.65","healthStatus":"moderate","coverage":"89,000 ha","satellite":"Sentinel-2","lastCapture":"2026-05-13","status":"active"},{"id":"SAT-003","name":"Ogun Cassava Farms \u2014 NDVI","category":"vegetation","ndvi":"0.78","healthStatus":"excellent","coverage":"45,000 ha","satellite":"Landsat-9","lastCapture":"2026-05-12","status":"active"},{"id":"SAT-004","name":"Kebbi Rice Paddy \u2014 Flood Risk","category":"flood","riskLevel":"moderate","coverage":"67,000 ha","satellite":"Sentinel-1","lastCapture":"2026-05-14","status":"alert"}],
  cooperative_credit_scoring: [{"id":"CCS-001","name":"Kano Groundnut Coop","category":"scoring","coopScore":82,"repaymentHistory":"94%","governanceScore":78,"productionVolume":"high","riskGrade":"A","status":"active"},{"id":"CCS-002","name":"Ogun Cassava Union","category":"scoring","coopScore":75,"repaymentHistory":"91%","governanceScore":72,"productionVolume":"medium","riskGrade":"B+","status":"active"},{"id":"CCS-003","name":"Benue Rice Association","category":"scoring","coopScore":68,"repaymentHistory":"88%","governanceScore":65,"productionVolume":"high","riskGrade":"B","status":"active"},{"id":"CCS-004","name":"Enugu Palm Oil Producers","category":"scoring","coopScore":58,"repaymentHistory":"82%","governanceScore":55,"productionVolume":"low","riskGrade":"C+","status":"forming"}],
  fisheries_aquaculture: [{"id":"FISH-001","name":"Kebbi Catfish Farm","category":"catfish","pondCount":12,"fingerlings":45000,"feedCycle":"Day 120/180","expectedHarvest":"22.5 MT","owner":"Hajiya Amina","status":"active"},{"id":"FISH-002","name":"Lagos Tilapia Farm","category":"tilapia","pondCount":8,"fingerlings":32000,"feedCycle":"Day 90/150","expectedHarvest":"16 MT","owner":"Mr. Tunde Bakare","status":"active"},{"id":"FISH-003","name":"Delta Shrimp Farm","category":"shrimp","pondCount":6,"fingerlings":120000,"feedCycle":"Day 60/120","expectedHarvest":"8 MT","owner":"Chief Ovie Omo-Agege","status":"active"}],
  farm_boundary_mapping: [{"id":"FBM-001","name":"Musa Abdullahi \u2014 Kano","category":"boundary","areaHa":12.5,"coordinates":"11.9964\u00b0N, 8.5167\u00b0E","verified":true,"overlapCheck":"clear","cropType":"wheat","status":"verified"},{"id":"FBM-002","name":"Bola Adeyemi \u2014 Ogun","category":"boundary","areaHa":8.2,"coordinates":"7.1475\u00b0N, 3.3619\u00b0E","verified":true,"overlapCheck":"clear","cropType":"cassava","status":"verified"},{"id":"FBM-003","name":"Simon Terkimbi \u2014 Benue","category":"boundary","areaHa":15.8,"coordinates":"7.7323\u00b0N, 8.5391\u00b0E","verified":false,"overlapCheck":"pending","cropType":"rice","status":"pending"}],
  area_yield_index_insurance: [{"id":"AYII-001","name":"Kano Wheat AYII \u2014 2026","category":"AYII","coverage":"125,000 ha","triggerYield":"2.8 MT/ha","actualYield":"pending","premium":"\u20a64,500/ha","sumInsured":"\u20a6180,000/ha","status":"active"},{"id":"AYII-002","name":"Benue Rice AYII \u2014 2026","category":"AYII","coverage":"89,000 ha","triggerYield":"3.5 MT/ha","actualYield":"pending","premium":"\u20a65,200/ha","sumInsured":"\u20a6220,000/ha","status":"active"},{"id":"AYII-003","name":"Ogun Cassava AYII \u2014 2026","category":"AYII","coverage":"45,000 ha","triggerYield":"15 MT/ha","actualYield":"pending","premium":"\u20a63,800/ha","sumInsured":"\u20a6150,000/ha","status":"active"}],
  warehouse_management: [{"id":"WH-001","name":"Kano Central Warehouse","category":"grain","capacity":"50,000 MT","currentStock":"32,400 MT","utilization":"64.8%","commodities":"Wheat, Maize, Sorghum","status":"active","lastFumigation":"2026-04-28"},{"id":"WH-002","name":"Benue Rice Silo","category":"rice","capacity":"25,000 MT","currentStock":"18,200 MT","utilization":"72.8%","commodities":"Paddy Rice, Milled Rice","status":"active","lastFumigation":"2026-05-05"},{"id":"WH-003","name":"Ogun Cassava Store","category":"tuber","capacity":"15,000 MT","currentStock":"8,900 MT","utilization":"59.3%","commodities":"Cassava Chips, Garri, Starch","status":"active","lastFumigation":"2026-04-20"}],
  agent_farmer_onboarding: [{"id":"AFO-001","name":"Agent Musa \u2014 Kano Zone","category":"agent","farmersOnboarded":245,"monthlyTarget":300,"completion":"81.7%","zone":"Kano/Jigawa","status":"active","lastSync":"2026-05-14"},{"id":"AFO-002","name":"Agent Bola \u2014 Ogun Zone","category":"agent","farmersOnboarded":180,"monthlyTarget":200,"completion":"90%","zone":"Ogun/Oyo","status":"active","lastSync":"2026-05-14"},{"id":"AFO-003","name":"Agent Simon \u2014 Benue Zone","category":"agent","farmersOnboarded":320,"monthlyTarget":350,"completion":"91.4%","zone":"Benue/Nasarawa","status":"active","lastSync":"2026-05-13"}],
  livestock_insurance: [{"id":"LI-001","name":"Cattle Mortality \u2014 Adamawa","category":"mortality","headsCovered":1250,"premium":"\u20a612.5M","sumInsured":"\u20a6625M","triggerType":"mortality","status":"active","policyPeriod":"2026-01 to 2026-12"},{"id":"LI-002","name":"Poultry Disease \u2014 Oyo","category":"disease","headsCovered":25000,"premium":"\u20a64.2M","sumInsured":"\u20a687.5M","triggerType":"disease_outbreak","status":"active","policyPeriod":"2026-01 to 2026-12"},{"id":"LI-003","name":"IBLI Pastoralist \u2014 Sokoto","category":"IBLI","headsCovered":800,"premium":"\u20a62.4M","sumInsured":"\u20a6120M","triggerType":"NDVI_index","status":"active","policyPeriod":"2026-04 to 2027-03"}],
  equipment_leasing: [{"id":"EQL-001","name":"John Deere 5075E Tractor","category":"tractor","leasee":"Kano Wheat Coop","monthlyPayment":"\u20a6450,000","tenure":"36 months","remaining":"28 months","value":"\u20a618M","status":"active"},{"id":"EQL-002","name":"Rice Mill (2 MT/hr)","category":"processing","leasee":"Benue Rice Association","monthlyPayment":"\u20a6280,000","tenure":"24 months","remaining":"18 months","value":"\u20a68.5M","status":"active"},{"id":"EQL-003","name":"Boom Sprayer (600L)","category":"sprayer","leasee":"Ogun Cassava Union","monthlyPayment":"\u20a685,000","tenure":"12 months","remaining":"6 months","value":"\u20a61.8M","status":"active"}],
  crop_yield_prediction: [{"id":"YLD-001","name":"Wheat Yield \u2014 Kano 2026","category":"prediction","predictedYield":"3.2 MT/ha","confidence":"87%","factors":"rainfall, NDVI, soil","model":"XGBoost-v3","status":"active","cropType":"wheat"},{"id":"YLD-002","name":"Rice Yield \u2014 Benue 2026","category":"prediction","predictedYield":"4.1 MT/ha","confidence":"82%","factors":"rainfall, temperature, NDVI","model":"XGBoost-v3","status":"active","cropType":"rice"},{"id":"YLD-003","name":"Maize Yield \u2014 Kaduna 2026","category":"prediction","predictedYield":"2.8 MT/ha","confidence":"85%","factors":"rainfall, soil, planting_date","model":"XGBoost-v3","status":"active","cropType":"maize"}],
  multi_peril_crop_insurance: [{"id":"MPCI-001","name":"Kano Wheat MPCI \u2014 2026","category":"MPCI","coverage":"drought, flood, pest, hail, fire","premium":"\u20a68,200/ha","sumInsured":"\u20a6280,000/ha","areaCovered":"12,500 ha","status":"active"},{"id":"MPCI-002","name":"Benue Rice MPCI \u2014 2026","category":"MPCI","coverage":"flood, pest, disease, wildlife","premium":"\u20a67,500/ha","sumInsured":"\u20a6250,000/ha","areaCovered":"8,900 ha","status":"active"},{"id":"MPCI-003","name":"Ogun Cassava MPCI \u2014 2026","category":"MPCI","coverage":"disease, pest, theft, fire","premium":"\u20a65,800/ha","sumInsured":"\u20a6180,000/ha","areaCovered":"4,500 ha","status":"active"}],
  agri_logistics: [{"id":"LOG-001","name":"Kano \u2192 Lagos Grain Convoy","category":"transport","commodity":"Wheat","tonnage":"240 MT","trucks":8,"route":"Kano-Abuja-Lagos","status":"in_transit","eta":"2026-05-16"},{"id":"LOG-002","name":"Benue \u2192 Onitsha Rice Shipment","category":"transport","commodity":"Rice","tonnage":"120 MT","trucks":4,"route":"Makurdi-Enugu-Onitsha","status":"in_transit","eta":"2026-05-15"},{"id":"LOG-003","name":"Ogun \u2192 Lagos Cold Chain","category":"cold_chain","commodity":"Cassava Products","tonnage":"45 MT","trucks":2,"route":"Abeokuta-Lagos","status":"delivered","eta":"2026-05-14"}],
  cbn_agri_returns: [{"id":"CBN-AR-001","name":"Q1 2026 Agricultural Lending Report","category":"quarterly","reportType":"CBN-AGL-Q","totalLoanBook":"\u20a648.5B","disbursed":"\u20a612.2B","repaid":"\u20a68.9B","npl":"3.2%","status":"filed","filingDate":"2026-04-30"},{"id":"CBN-AR-002","name":"April 2026 ACGSF Return","category":"monthly","reportType":"ACGSF-M","guaranteedLoans":"\u20a62.8B","claims":"\u20a645M","newGuarantees":"\u20a6380M","status":"filed","filingDate":"2026-05-10"},{"id":"CBN-AR-003","name":"Q1 2026 NIRSAL CRG Report","category":"quarterly","reportType":"NIRSAL-Q","guaranteedPortfolio":"\u20a68.2B","activeCRGs":45,"claimsFiled":2,"status":"filed","filingDate":"2026-04-28"}],
  animal_id_traceability: [{"id":"AID-001","name":"RFID Tag \u2014 WF-KN-2024-001","category":"cattle","tagType":"RFID","breed":"White Fulani","location":"Kano","owner":"Modibbo Livestock","lastMovement":"2026-05-10","vaccinationStatus":"current","status":"active"},{"id":"AID-002","name":"RFID Tag \u2014 RS-SK-2024-045","category":"goat","tagType":"RFID","breed":"Red Sokoto","location":"Sokoto","owner":"Danfodio Enterprise","lastMovement":"2026-05-08","vaccinationStatus":"current","status":"active"},{"id":"AID-003","name":"RFID Tag \u2014 BR-OY-2024-112","category":"poultry","tagType":"batch","breed":"Broiler","location":"Ibadan","owner":"Funke Farms","lastMovement":"2026-05-12","vaccinationStatus":"current","status":"active"}],
  nirsal_agro_geocoop: [{"id":"NAGC-001","name":"Kano Wheat Cluster \u2014 Zone A","category":"geocoop","farmers":245,"areaHa":3250,"centroid":"11.9964\u00b0N, 8.5167\u00b0E","satelliteVerified":true,"productionMT":9750,"status":"verified"},{"id":"NAGC-002","name":"Benue Rice Cluster \u2014 Zone B","category":"geocoop","farmers":320,"areaHa":5060,"centroid":"7.7323\u00b0N, 8.5391\u00b0E","satelliteVerified":true,"productionMT":20240,"status":"verified"},{"id":"NAGC-003","name":"Kebbi Rice Cluster \u2014 Zone C","category":"geocoop","farmers":180,"areaHa":2700,"centroid":"12.4539\u00b0N, 4.1975\u00b0E","satelliteVerified":false,"productionMT":0,"status":"pending"}],
  agri_iot_sensor: [{"id":"IOT-001","name":"Soil Moisture \u2014 Kano Field A","category":"soil","sensorType":"capacitive","reading":"28%","threshold":"25-35%","battery":"82%","lastPing":"2026-05-14 10:15","status":"active"},{"id":"IOT-002","name":"Weather Station \u2014 Benue","category":"weather","sensorType":"multi","reading":"32\u00b0C, 65% RH","threshold":"N/A","battery":"95%","lastPing":"2026-05-14 10:20","status":"active"},{"id":"IOT-003","name":"Water Level \u2014 Kebbi Irrigation","category":"water","sensorType":"ultrasonic","reading":"1.8m","threshold":"1.5-2.5m","battery":"78%","lastPing":"2026-05-14 10:10","status":"active"}],
  agri_reinsurance: [{"id":"REIN-001","name":"Swiss Re \u2014 AYII Treaty 2026","category":"treaty","cedant":"54Bank Insurance","reinsurer":"Swiss Re","treaty":"quota_share","cession":"60%","premium":"\u20a62.4B","status":"active"},{"id":"REIN-002","name":"Munich Re \u2014 Livestock XoL","category":"excess_of_loss","cedant":"54Bank Insurance","reinsurer":"Munich Re","treaty":"XoL","retention":"\u20a650M","limit":"\u20a6500M","status":"active"},{"id":"REIN-003","name":"Africa Re \u2014 MPCI Treaty","category":"treaty","cedant":"54Bank Insurance","reinsurer":"Africa Re","treaty":"quota_share","cession":"40%","premium":"\u20a61.8B","status":"active"}],
  quality_certification: [{"id":"QC-001","name":"NAFDAC \u2014 Garri Export Grade","category":"NAFDAC","product":"Garri","producer":"Ogun Cassava Union","certNumber":"NAFDAC/A7-1234","expiryDate":"2027-06-30","status":"certified"},{"id":"QC-002","name":"SON \u2014 Rice NIS-451:2020","category":"SON","product":"Milled Rice","producer":"Benue Rice Mills","certNumber":"SON/MAS/RC-5678","expiryDate":"2027-03-15","status":"certified"},{"id":"QC-003","name":"NAFDAC \u2014 Honey Export","category":"NAFDAC","product":"Raw Honey","producer":"Plateau Beekeepers","certNumber":"NAFDAC/A7-9012","expiryDate":"2027-09-30","status":"pending"}],
  agri_esg_impact: [{"id":"ESG-001","name":"SDG 1 \u2014 Poverty Reduction","category":"social","metric":"Income improvement","baseline":"\u20a6180K/yr","current":"\u20a6420K/yr","improvement":"+133%","beneficiaries":"12,400 farmers","status":"active"},{"id":"ESG-002","name":"SDG 2 \u2014 Zero Hunger","category":"social","metric":"Food production increase","baseline":"45,000 MT","current":"89,000 MT","improvement":"+97.8%","beneficiaries":"6 states","status":"active"},{"id":"ESG-003","name":"SDG 13 \u2014 Climate Action","category":"environmental","metric":"Carbon sequestration","baseline":"0 tonnes CO2e","current":"12,400 tonnes CO2e","improvement":"N/A","beneficiaries":"45,000 ha","status":"active"}],
  crossborder_agri_trade: [{"id":"CBT-001","name":"Cocoa Export \u2014 Nigeria \u2192 EU","category":"export","commodity":"Cocoa Beans","volume":"2,400 MT","value":"$12.8M","corridor":"Lagos \u2192 Rotterdam","mojaloop":"enabled","status":"active"},{"id":"CBT-002","name":"Cashew Export \u2014 Nigeria \u2192 India","category":"export","commodity":"Raw Cashew Nuts","volume":"5,800 MT","value":"$8.4M","corridor":"Lagos \u2192 Mumbai","mojaloop":"enabled","status":"active"},{"id":"CBT-003","name":"Sesame Export \u2014 Nigeria \u2192 Japan","category":"export","commodity":"Sesame Seeds","volume":"3,200 MT","value":"$6.2M","corridor":"Lagos \u2192 Yokohama","mojaloop":"enabled","status":"in_transit"}],
  cooperative_meetings: [{"id":"MTG-001","name":"Kano Coop Q2 General Meeting","category":"general","cooperative":"Kano Groundnut Coop","date":"2026-05-20","attendance":"212/245","agenda":"Q1 financials, election, bylaws amendment","status":"scheduled"},{"id":"MTG-002","name":"Ogun Coop Monthly Review","category":"monthly","cooperative":"Ogun Cassava Union","date":"2026-05-15","attendance":"pending","agenda":"Production targets, input distribution","status":"scheduled"},{"id":"MTG-003","name":"Benue Coop AGM 2026","category":"agm","cooperative":"Benue Rice Association","date":"2026-06-15","attendance":"pending","agenda":"Annual report, dividend, board election","status":"planned"}],
  cooperative_financials: [{"id":"CF-001","name":"Kano Groundnut Coop \u2014 P&L 2025","category":"financial","revenue":"\u20a6245M","expenses":"\u20a6198M","netIncome":"\u20a647M","memberEquity":"\u20a689M","auditStatus":"audited","status":"completed"},{"id":"CF-002","name":"Ogun Cassava Union \u2014 P&L 2025","category":"financial","revenue":"\u20a6180M","expenses":"\u20a6152M","netIncome":"\u20a628M","memberEquity":"\u20a662M","auditStatus":"audited","status":"completed"},{"id":"CF-003","name":"Benue Rice Association \u2014 P&L 2025","category":"financial","revenue":"\u20a6320M","expenses":"\u20a6278M","netIncome":"\u20a642M","memberEquity":"\u20a6105M","auditStatus":"in_progress","status":"pending"}],
  soil_analysis: [{"id":"SOIL-001","name":"Kano \u2014 Plot A (Wheat)","category":"analysis","ph":6.8,"nitrogen":"medium","phosphorus":"high","potassium":"medium","organicMatter":"2.1%","texture":"Sandy loam","recommendation":"Apply 80kg N/ha","status":"completed"},{"id":"SOIL-002","name":"Benue \u2014 Plot B (Rice)","category":"analysis","ph":5.9,"nitrogen":"low","phosphorus":"medium","potassium":"low","organicMatter":"3.2%","texture":"Clay loam","recommendation":"Apply 120kg N/ha + 60kg K/ha","status":"completed"},{"id":"SOIL-003","name":"Ogun \u2014 Plot C (Cassava)","category":"analysis","ph":6.2,"nitrogen":"medium","phosphorus":"low","potassium":"medium","organicMatter":"2.8%","texture":"Sandy clay","recommendation":"Apply 40kg P/ha","status":"completed"}],
  insurance_portfolio_analytics: [{"id":"IPA-001","name":"Crop Insurance Portfolio \u2014 2026","category":"analytics","totalPolicies":12500,"totalPremium":"\u20a68.2B","lossRatio":"42%","combinedRatio":"68%","claimsCount":890,"status":"active"},{"id":"IPA-002","name":"Livestock Insurance Portfolio \u2014 2026","category":"analytics","totalPolicies":3200,"totalPremium":"\u20a62.4B","lossRatio":"35%","combinedRatio":"62%","claimsCount":245,"status":"active"},{"id":"IPA-003","name":"AYII Portfolio \u2014 2026","category":"analytics","totalPolicies":8900,"totalPremium":"\u20a64.8B","lossRatio":"28%","combinedRatio":"55%","claimsCount":120,"status":"active"}],
  parametric_insurance_iot: [{"id":"PII-001","name":"Drought Trigger \u2014 Kano Zone","category":"parametric","triggerType":"rainfall","threshold":"<200mm/60days","currentReading":"185mm","payoutStatus":"monitoring","autoPayoutAmount":"\u20a6180,000/ha","status":"alert"},{"id":"PII-002","name":"Flood Trigger \u2014 Benue Zone","category":"parametric","triggerType":"river_level","threshold":">8.5m","currentReading":"7.2m","payoutStatus":"normal","autoPayoutAmount":"\u20a6220,000/ha","status":"active"},{"id":"PII-003","name":"Temperature Trigger \u2014 Plateau","category":"parametric","triggerType":"temperature","threshold":">38\u00b0C for 5 days","currentReading":"34\u00b0C","payoutStatus":"normal","autoPayoutAmount":"\u20a6150,000/ha","status":"active"}],
  post_harvest_loss_tracker: [{"id":"PHL-001","name":"Maize Storage Loss \u2014 Kano","category":"storage","commodity":"Maize","initialQuantity":"5,000 MT","lossQuantity":"125 MT","lossRate":"2.5%","cause":"weevil infestation","preventionCost":"\u20a68.5M","status":"active"},{"id":"PHL-002","name":"Rice Transport Loss \u2014 Benue","category":"transport","commodity":"Paddy Rice","initialQuantity":"2,400 MT","lossQuantity":"48 MT","lossRate":"2.0%","cause":"spillage, moisture","preventionCost":"\u20a63.2M","status":"active"},{"id":"PHL-003","name":"Tomato Spoilage \u2014 Kaduna","category":"spoilage","commodity":"Fresh Tomato","initialQuantity":"800 MT","lossQuantity":"320 MT","lossRate":"40%","cause":"no cold chain","preventionCost":"\u20a612M","status":"critical"}],
  aggregation_center: [{"id":"AGC-001","name":"Kano Grain Buying Center","category":"buying","location":"Dawanau Market, Kano","commodities":"Wheat, Maize, Sorghum","dailyThroughput":"450 MT","farmersServed":"1,200/week","status":"active"},{"id":"AGC-002","name":"Benue Rice Collection Point","category":"collection","location":"Makurdi","commodities":"Paddy Rice","dailyThroughput":"180 MT","farmersServed":"600/week","status":"active"},{"id":"AGC-003","name":"Ogun Cassava Hub","category":"processing","location":"Abeokuta","commodities":"Cassava, Garri, Starch","dailyThroughput":"120 MT","farmersServed":"400/week","status":"active"}],
  cbn_agsmeis: [{"id":"AGS-001","name":"Kano Agri Processing \u2014 AGSMEIS","category":"AGSMEIS","applicant":"Musa Abdullahi Enterprise","amount":"\u20a610M","purpose":"Grain processing mill","status":"approved","disbursementDate":"2026-04-15","repaymentStart":"2027-04-15"},{"id":"AGS-002","name":"Ogun Cassava Value Chain \u2014 AGSMEIS","category":"AGSMEIS","applicant":"Bola Farms Ltd","amount":"\u20a68M","purpose":"Cassava processing plant","status":"disbursed","disbursementDate":"2026-03-01","repaymentStart":"2027-03-01"},{"id":"AGS-003","name":"Benue Rice Milling \u2014 AGSMEIS","category":"AGSMEIS","applicant":"Simon Rice Mills","amount":"\u20a615M","purpose":"Rice milling equipment","status":"pending","disbursementDate":"pending","repaymentStart":"pending"}],
  acgsf_guarantee: [{"id":"ACGSF-001","name":"Kano Wheat Loan Guarantee","category":"ACGSF","guaranteeAmount":"\u20a645M","loanAmount":"\u20a660M","coverage":"75%","farmer":"Kano Wheat Coop","bank":"First Bank","status":"active","expiryDate":"2027-06-30"},{"id":"ACGSF-002","name":"Benue Rice Loan Guarantee","category":"ACGSF","guaranteeAmount":"\u20a630M","loanAmount":"\u20a640M","coverage":"75%","farmer":"Benue Rice Association","bank":"Zenith Bank","status":"active","expiryDate":"2027-09-15"},{"id":"ACGSF-003","name":"Ogun Cassava Loan Guarantee","category":"ACGSF","guaranteeAmount":"\u20a622.5M","loanAmount":"\u20a630M","coverage":"75%","farmer":"Ogun Cassava Union","bank":"GTBank","status":"pending","expiryDate":"2028-01-31"}],
};

export function registerAgricultureEnhancementRoutes(app: Express): void {
  for (const svc of AGRI_SERVICES) {
    const proxyUrl = `http://localhost:${svc.port}/v1/${svc.topic}/list`;

    app.get(`/api/agriculture-enhancement/${svc.path}/list`, async (_req, res) => {
      try {
        const ctrl = new AbortController();
        const timer = setTimeout(() => ctrl.abort(), 3000);
        const resp = await fetch(proxyUrl, { signal: ctrl.signal });
        clearTimeout(timer);
        const data = await resp.json();
        res.json(data);
      } catch {
        const items = SEED_DATA[svc.topic] || [];
        res.json({ items, total: items.length, service: svc.name, fallback: true });
      }
    });

    app.get(`/api/agriculture-enhancement/${svc.path}/healthz`, async (_req, res) => {
      try {
        const ctrl = new AbortController();
        const timer = setTimeout(() => ctrl.abort(), 3000);
        const resp = await fetch(`http://localhost:${svc.port}/healthz`, { signal: ctrl.signal });
        clearTimeout(timer);
        const data = await resp.json();
        res.json(data);
      } catch {
        res.json({ status: "unavailable", service: svc.name, fallback: true });
      }
    });
  }
}
