import { toCamelCase, toUpperCase } from '../utils/textCaseUtils';
// Server response interfaces
export interface TenantServerResponse {
  message: string;
  tenant: TenantData;
}

export interface TenantData {
  id: number;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  name: string;
  status: 'active' | 'inactive' | 'suspended';
  tenant_id: string;
  tenant_secret: string;
  status_message: string | null;
  contact: TenantContactData;
  branding: TenantBrandingData;
  feature_flags: FeatureFlag[];
}

export interface TenantContactData {
  id: string;
  name: string;
  email: string;
  phone: string;
}

export interface TenantBrandingData {
  id: string;
  logo_url: string;
  favicon_url: string;
  primary_color: string;
  secondary_color: string;
  domain: string;
  accent_color?: string;
  background_color?: string;
  surface_color?: string;
  error_color?: string;
  warning_color?: string;
  success_color?: string;
  text_primary_color?: string;
  text_secondary_color?: string;
  border_radius?: number;
  font_family?: string;
  custom_css?: string;
}

export interface FeatureFlag {
  id: string;
  name: string;
  is_enabled: boolean;
  config: Record<string, any>;
}

// Client-side normalized interfaces
export interface TenantConfig {
  id: string;
  name: string;
  displayName: string;
  domain: string;
  logo: string;
  favicon: string;
  status: 'active' | 'inactive' | 'suspended';
  branding: TenantBranding;
  feature_flags: TenantFeatures;
  /**
   * Compatibility: features is an alias for feature_flags (camelCase)
   */
  features?: TenantFeatures;
  contact: TenantContact;
  metadata?: TenantMetadata;
}

export interface TenantBranding {
  primary_color: string;
  secondary_color: string;
  accentColor?: string;
  backgroundColor: string;
  surfaceColor: string;
  errorColor?: string;
  warningColor?: string;
  successColor?: string;
  textPrimaryColor: string;
  textSecondaryColor: string;
  borderRadius?: number;
  fontFamily?: string;
  customCSS?: string;
}

export interface TenantFeatures {
  payments?: boolean;
  loans?: boolean;
  insurance?: boolean;
  auth?: boolean;
  userManagement?: boolean;
  accounts?: boolean;
  reporting?: boolean;
  savings?: boolean;
  notifications?: boolean;
  compliance?: boolean;
  kycKyb?: boolean;
  lpo?: boolean;
  dispute?: boolean;
  esusu?: boolean;
  escrow?: boolean;
  mortgage?: boolean;
  educationLoans?: boolean;
  agricultureFinance?: boolean;
  islamicBanking?: boolean;
  carbonCredits?: boolean;
  supplyChainFinance?: boolean;
  etherisc?: boolean;
  finance?: boolean;
  fx?: boolean;
  virtualAccounts?: boolean;
  chartOfAccounts?: boolean;
  teller?: boolean;
  treasury?: boolean;
  cardManagement?: boolean;
  fraudDetection?: boolean;
  reconciliation?: boolean;
  riskManagement?: boolean;
  relationshipManager?: boolean;
  communicationHub?: boolean;
  erpIntegration?: boolean;
  audit?: boolean;
  temporalAccess?: boolean;
  tradeFinance?: boolean;
  documentManagement?: boolean;
  employeeManagement?: boolean;
  merchantManagement?: boolean;
  developerPlatform?: boolean;
  // Legacy enable-prefix flags (auto-generated by transformTenantData)
  enableBiometrics?: boolean;
  enableQRPayments?: boolean;
  enablePushNotifications?: boolean;
  enableLPO?: boolean;
  enableCarbonCredits?: boolean;
  enableCards?: boolean;
  enableBillPayments?: boolean;
  enableRewards?: boolean;
  enableIslamicBanking?: boolean;
  enableVoiceBanking?: boolean;
  // Feature configs
  authConfig?: Record<string, any>;
  accountsConfig?: Record<string, any>;
  [key: string]: boolean | Record<string, any> | undefined;
}

export interface TenantContact {
  id?: string;
  name?: string;
  email: string;
  phone: string;
  supportUrl?: string;
  address?: string;
  socialMedia?: {
    facebook?: string;
    twitter?: string;
    instagram?: string;
    linkedin?: string;
  };
}

export interface TenantMetadata {
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
}

/**
 * Transform server response to client-side TenantConfig
 */
export const transformTenantData = (serverData: TenantData): TenantConfig => {
  // Transform feature flags array to features object
  // Store both snake_case, camelCase, and enable* versions for compatibility
  const features: TenantFeatures = {};
  serverData.feature_flags.forEach(flag => {
    // Store with original snake_case name
    features[flag.name] = flag.is_enabled;
    // Also store camelCase version for compatibility
    const camelCaseName = toCamelCase(flag.name);
    if (camelCaseName !== flag.name) {
      features[camelCaseName] = flag.is_enabled;
    }
    // Store with enable* prefix for legacy compatibility (e.g., lpo -> enableLPO, cards -> enableCards)
    // Known acronyms that should be all uppercase
    const acronyms = ['lpo', 'qr', 'api'];
    let enablePrefixName: string;
    if (flag.name.includes('_')) {
      // Has underscores: carbon_credits -> carbonCredits -> enableCarbonCredits
      enablePrefixName = 'enable' + camelCaseName.charAt(0).toUpperCase() + camelCaseName.slice(1);
    } else if (acronyms.includes(flag.name.toLowerCase())) {
      // Known acronym: lpo -> enableLPO
      enablePrefixName = 'enable' + toUpperCase(flag.name);
    } else {
      // Regular name: cards -> enableCards
      enablePrefixName = 'enable' + camelCaseName.charAt(0).toUpperCase() + camelCaseName.slice(1);
    }
    features[enablePrefixName] = flag.is_enabled;
    
    // Store config if it exists
    if (Object.keys(flag.config).length > 0) {
      features[`${flag.name}Config`] = flag.config;
      if (camelCaseName !== flag.name) {
        features[`${camelCaseName}Config`] = flag.config;
      }
      features[`${enablePrefixName}Config`] = flag.config;
    }
  });

  return {
    id: serverData.tenant_id,
    name: serverData.name,
    displayName: serverData.name,
    domain: serverData.branding.domain,
    logo: serverData.branding.logo_url,
    favicon: serverData.branding.favicon_url,
    status: serverData.status,
    branding: {
      primary_color: (serverData.branding.primary_color && serverData.branding.primary_color.trim()) || '#1a73e8',
      secondary_color: (serverData.branding.secondary_color && serverData.branding.secondary_color.trim()) || '#34a853',
      accentColor: serverData.branding.accent_color,
      backgroundColor: serverData.branding.background_color || '#F5F7FA',
      surfaceColor: serverData.branding.surface_color || '#FFFFFF',
      errorColor: serverData.branding.error_color || '#D32F2F',
      warningColor: serverData.branding.warning_color || '#FFA726',
      successColor: serverData.branding.success_color || '#66BB6A',
      textPrimaryColor: serverData.branding.text_primary_color || '#212121',
      textSecondaryColor: serverData.branding.text_secondary_color || '#757575',
      borderRadius: serverData.branding.border_radius || 12,
      fontFamily: serverData.branding.font_family || 'Roboto, sans-serif',
      customCSS: serverData.branding.custom_css,
    },
    feature_flags: features,
    contact: {
      id: serverData.contact.id,
      name: serverData.contact.name,
      email: serverData.contact.email,
      phone: serverData.contact.phone,
    },
    metadata: {
      createdAt: serverData.created_at,
      updatedAt: serverData.updated_at,
      deletedAt: serverData.deleted_at,
    },
  };
};

// Default 54link-dev tenant configuration (used as fallback)
export const DEFAULT_TENANT_DATA: TenantServerResponse = {
  message: 'success',
  tenant: {
    id: 1,
    created_at: '2025-12-10T10:55:44.948Z',
    updated_at: '2025-12-10T10:55:44.948Z',
    deleted_at: null,
    name: '54link-dev',
    status: 'active',
    tenant_id: '54link-dev',
    tenant_secret: '$2b$10$WHarvgiv8fHLuiWB43N35..f4o0WFrlYk34U3rqIQuaRFXJjSx4S2',
    status_message: null,
    contact: {
      id: '1db9f3a1-8b0c-4b19-b10b-520d50f30b23',
      name: '54link-dev Support',
      email: 'support@54link-dev.com',
      phone: '+234-800-54link-dev',
    },
    branding: {
      id: '19452aee-840b-4f31-a234-15bc43300b2a',
      logo_url: '/icons/logo.png',
      favicon_url: '/icons/favicon.ico',
      primary_color: '#1E3A8A',
      secondary_color: '#3B82F6',
      domain: '54link-dev.com',
    },
    feature_flags: [
      {
        id: '902e3745-9103-4864-a658-8ae6b8f670e5',
        name: 'payments',
        is_enabled: true,
        config: {},
      },
      {
        id: '60928203-65cd-4690-9d39-e621bb90ef01',
        name: 'loans',
        is_enabled: true,
        config: {},
      },
      {
        id: 'f8ecb050-041f-4bc7-b812-9604414d5d6c',
        name: 'insurance',
        is_enabled: true,
        config: {},
      },
      {
        id: '3c1b2edf-a5f0-43e3-b0ef-f87e041c6861',
        name: 'auth',
        is_enabled: true,
        config: {
          realm: '51link_54link-dev',
          public_rsa_key:
            'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3RWvyq55AnZjQ5VIEVjdRPBfvwdMJTMT3tVel94cI9sim25ePnMUOpWdQdSt+NGmMFkEa42ys9e/+NVdnCA9/WjPw10M+gzFM6Ml913o6smwl5qTAvvYJnK3QlUisrt0sul617gfx6aRS6nt/W4f297R0I3p12R/nLpCaqZ5TYIQkTpCewab3mHmsJr+cnrD6mJC5Gfkzrl2HtqaHokPucYs/ClyogdT0aALpXoi7EQsYGlUp4W94ZLx9XD9XaHPxCZk+qobeKVU3Z0CxWp60CPdeJviHehOWTfFwyH1WAkoTFBoCexbH4BzqWJRTn4h3N0ES2DBXyu6CMwEalETLQIDAQAB',
        },
      },
      {
        id: 'bb6cfdd8-7318-46aa-8b41-1f6430d5de04',
        name: 'user_management',
        is_enabled: true,
        config: {},
      },
      {
        id: '20b3662e-865a-4d3d-a383-15f2b53fc4e2',
        name: 'accounts',
        is_enabled: true,
        config: {
          account: {
            id: 1,
            name: 'mint_account',
            status: 'active',
            ledger_id: '1',
            tenant_id: '54link-dev',
            created_at: '2025-12-10 11:51:56',
            deleted_at: null,
            updated_at: '2025-12-10 11:51:56',
            keycloak_id: 'mint_account_54link-dev',
            account_number: '5400000001',
          },
          message: 'Success',
        },
      },
      {
        id: 'b734fb51-6b5a-43e2-ae6c-817fb4a88800',
        name: 'reporting',
        is_enabled: true,
        config: {},
      },
      {
        id: 'c734fb51-6b5a-43e2-ae6c-817fb4a88801',
        name: 'cards',
        is_enabled: true,
        config: {},
      },
      {
        id: 'd734fb51-6b5a-43e2-ae6c-817fb4a88802',
        name: 'rewards',
        is_enabled: true,
        config: {},
      },
      { id: 'e001', name: 'savings',              is_enabled: true,  config: {} },
      { id: 'e002', name: 'notifications',        is_enabled: true,  config: {} },
      { id: 'e003', name: 'compliance',           is_enabled: true,  config: {} },
      { id: 'e004', name: 'kyc_kyb',              is_enabled: true,  config: {} },
      { id: 'e005', name: 'lpo',                  is_enabled: true,  config: {} },
      { id: 'e006', name: 'dispute',              is_enabled: true,  config: {} },
      { id: 'e007', name: 'esusu',                is_enabled: true,  config: {} },
      { id: 'e008', name: 'escrow',               is_enabled: true,  config: {} },
      { id: 'e009', name: 'mortgage',             is_enabled: true,  config: {} },
      { id: 'e010', name: 'education_loans',      is_enabled: true,  config: {} },
      { id: 'e011', name: 'agriculture_finance',  is_enabled: true,  config: {} },
      { id: 'e012', name: 'islamic_banking',      is_enabled: true,  config: {} },
      { id: 'e013', name: 'carbon_credits',       is_enabled: true,  config: {} },
      { id: 'e014', name: 'supply_chain_finance', is_enabled: true,  config: {} },
      { id: 'e015', name: 'etherisc',             is_enabled: true,  config: {} },
      { id: 'e016', name: 'finance',              is_enabled: true,  config: {} },
      { id: 'e017', name: 'fx',                   is_enabled: true,  config: {} },
      { id: 'e018', name: 'virtual_accounts',     is_enabled: true,  config: {} },
      { id: 'e019', name: 'chart_of_accounts',    is_enabled: true,  config: {} },
      { id: 'e020', name: 'teller',               is_enabled: true,  config: {} },
      { id: 'e021', name: 'treasury',             is_enabled: true,  config: {} },
      { id: 'e022', name: 'card_management',      is_enabled: true,  config: {} },
      { id: 'e023', name: 'fraud_detection',      is_enabled: true,  config: {} },
      { id: 'e024', name: 'reconciliation',       is_enabled: true,  config: {} },
      { id: 'e025', name: 'risk_management',      is_enabled: true,  config: {} },
      { id: 'e026', name: 'relationship_manager', is_enabled: true,  config: {} },
      { id: 'e027', name: 'communication_hub',    is_enabled: true,  config: {} },
      { id: 'e028', name: 'erp_integration',      is_enabled: true,  config: {} },
      { id: 'e029', name: 'audit',                is_enabled: true,  config: {} },
      { id: 'e030', name: 'temporal_access',      is_enabled: true,  config: {} },
      { id: 'e031', name: 'trade_finance',        is_enabled: true,  config: {} },
      { id: 'e032', name: 'document_management',  is_enabled: true,  config: {} },
      { id: 'e033', name: 'employee_management',  is_enabled: true,  config: {} },
      { id: 'e034', name: 'merchant_management',  is_enabled: true,  config: {} },
      { id: 'e035', name: 'developer_platform',   is_enabled: true,  config: {} },
    ],
  },
};

// Transform default data to default tenant
export const DEFAULT_TENANT: TenantConfig = transformTenantData(DEFAULT_TENANT_DATA.tenant);
