replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54link-dev-etherisc-service
  pullPolicy: IfNotPresent
  tag: "0.0.2"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54link
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9162
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    ephemeral-storage: 1Gi
    cpu: 300m
    memory: 512Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: etherisc-service
  appPort: 9162
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  DATABASE_URL: "postgresql://doadmin:AVNS_MSy6CW3EGXnA8wJgkLv@db-postgresql-nyc1-18193-do-user-10555812-0.e.db.ondigitalocean.com:25060/link_core_banking?sslmode=require"
  DATABASE_URI: "postgresql://doadmin:AVNS_MSy6CW3EGXnA8wJgkLv@db-postgresql-nyc1-18193-do-user-10555812-0.e.db.ondigitalocean.com:25060/link_core_banking?sslmode=require"
  DATABASE_POOL_SIZE: "3"
  DB_HOST: db-postgresql-nyc1-18193-do-user-10555812-0.e.db.ondigitalocean.com
  DB_PORT: "25060"
  DB_NAME: link_core_banking
  DB_USER: doadmin
  DB_PASSWORD: AVNS_MSy6CW3EGXnA8wJgkLv
  REDIS_URL: redis-master.redis.svc.cluster.local:6379
  REDIS_HOST: redis-master.redis.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_PASSWORD: 3phHSv7qbAuZLb2pi9FWED2X
  KAFKA_BROKERS: mojaloop-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  KAFKA_BOOTSTRAP_SERVERS: mojaloop-kafka-cluster-kafka-bootstrap.kafka.svc:9092
  KAFKA_SECURITY_PROTOCOL: PLAINTEXT
  KEYCLOAK_URL: https://keycloak.servers.upi.dev
  AUTH_ENFORCER_URL: "http://auth-enforcer-rs.54link-dev.svc.cluster.local:8314"
  ALLOWED_ORIGINS: "*"
  DAPR_URL: "http://localhost:3500"
  DAPR_HTTP_PORT: "3500"
  DAPR_PUBSUB: pubsub
  TEMPORAL_ADDRESS: temporal-frontend.temporal.svc:7233
  TEMPORAL_NAMESPACE: "54link-dev"
  CHAINLINK_URL: "https://oracle.etherisc.com"
  APP_HOST: "0.0.0.0"
  APP_PORT: "9162"
  PORT: "9162"
  PORT_BASE: "9162"
  LOG_LEVEL: info
  SERVICE_GROUP: etherisc-service
  SERVICES: "etherisc-service"
