replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54link-dev-ai-data-pipeline
  pullPolicy: IfNotPresent
  tag: "0.0.1"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54link
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9100
    - port: 9101
    - port: 9102
    - port: 9103
    - port: 9104
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    ephemeral-storage: 2Gi
    cpu: 500m
    memory: 1Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: ai-data-pipeline
  appPort: 9104
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  APP_PORT: "9100"
  PORT_BASE: "9100"
  SERVICE_GROUP: ai-data-pipeline
  SERVICES: "data-intelligence,document-intelligence-py,lakehouse-etl-py,lakehouse-rs,materialized-view-engine-go"
