import CrudWorkspace from "@/components/CrudWorkspace";
import { Shield } from "lucide-react";

export default function EscrowWorkspace() {
  return (
    <CrudWorkspace
      config={{
        domainKey: "escrow",
        title: "Escrow — Multi-Party Escrow Management",
        subtitle: "Property, M&A, trade, litigation, construction, IP license, government, agriculture, energy escrow (Go :8186)",
        icon: Shield,
        accentColor: "text-blue-800",
        idField: "id",
        statusField: "status",
        searchFields: ["id", "escrowType", "condition", "currency"],
        apiBase: "/api/db/accounts",
        pageSize: 25,
        columns: [
          { key: "id", label: "Escrow ID" },
          { key: "escrowType", label: "Type", sortable: true },
          { key: "parties", label: "Parties", render: (v: any) => Array.isArray(v) ? v.map((p: any) => `${p.name} (${p.role})`).join(", ") : "—" },
          { key: "amount", label: "Amount", sortable: true, render: (v: any, row: any) => `${row?.currency === "USD" ? "$" : row?.currency === "GBP" ? "£" : row?.currency === "EUR" ? "€" : "₦"}${Number(v).toLocaleString()}` },
          { key: "currency", label: "Currency", sortable: true },
          { key: "interestRate", label: "Rate %", sortable: true, render: (v: any) => v ? `${v}%` : "—" },
          { key: "accruedInterest", label: "Accrued Interest", sortable: true, render: (v: any) => v ? `₦${Number(v).toLocaleString()}` : "₦0" },
          { key: "totalFeesCharged", label: "Fees Charged", render: (v: any) => v ? `₦${Number(v).toLocaleString()}` : "₦0" },
          { key: "condition", label: "Release Condition" },
          { key: "status", label: "Status", sortable: true },
          { key: "expiresAt", label: "Expires", sortable: true },
        ],
        fields: [
          { key: "escrowType", label: "Escrow Type", type: "select", options: ["property", "m_and_a", "trade", "litigation", "construction", "ip_license", "government_contract", "dispute_resolution", "agriculture", "energy"], required: true },
          { key: "amount", label: "Amount", type: "number", required: true },
          { key: "currency", label: "Currency", type: "select", options: ["NGN", "USD", "GBP", "EUR", "GHS"], required: true },
          { key: "condition", label: "Release Condition", type: "text", required: true },
          { key: "interestRate", label: "Interest Rate (%)", type: "number" },
          { key: "expiresAt", label: "Expiry Date", type: "text" },
          { key: "notes", label: "Notes", type: "text" },
        ],
        tabs: [
          {
            key: "parties",
            label: "Parties",
            apiBase: "/api/db/escrow-accounts",
            subPath: "parties",
            columns: [
              { key: "id", label: "Party ID" },
              { key: "role", label: "Role", sortable: true },
              { key: "name", label: "Name", sortable: true },
              { key: "accountId", label: "Account ID" },
              { key: "email", label: "Email" },
              { key: "kycStatus", label: "KYC", sortable: true },
              { key: "kybStatus", label: "KYB", sortable: true },
              { key: "sharePercent", label: "Share %", render: (v: any) => v ? `${v}%` : "—" },
            ],
          },
          {
            key: "milestones",
            label: "Milestones",
            apiBase: "/api/db/escrow-milestones",
            columns: [
              { key: "id", label: "Milestone ID" },
              { key: "description", label: "Description" },
              { key: "releaseAmount", label: "Release Amount", render: (v: any) => v ? `₦${Number(v).toLocaleString()}` : "—" },
              { key: "releasePercent", label: "Release %", render: (v: any) => v ? `${v}%` : "—" },
              { key: "dueDate", label: "Due Date", sortable: true },
              { key: "status", label: "Status", sortable: true },
              { key: "verifiedBy", label: "Verified By" },
              { key: "verifiedAt", label: "Verified At" },
              { key: "sequenceOrder", label: "Order", sortable: true },
            ],
          },
          {
            key: "transactions",
            label: "Transactions",
            apiBase: "/api/db/escrow-transactions",
            columns: [
              { key: "id", label: "TX ID" },
              { key: "type", label: "Type", sortable: true },
              { key: "amount", label: "Amount", sortable: true, render: (v: any) => `₦${Number(v).toLocaleString()}` },
              { key: "from", label: "From" },
              { key: "to", label: "To" },
              { key: "status", label: "Status", sortable: true },
              { key: "milestoneId", label: "Milestone" },
              { key: "narration", label: "Narration" },
              { key: "ledgerRef", label: "Ledger Ref" },
              { key: "timestamp", label: "Timestamp", sortable: true },
            ],
          },
          {
            key: "disputes",
            label: "Disputes",
            apiBase: "/api/db/escrow-disputes",
            columns: [
              { key: "id", label: "Dispute ID" },
              { key: "raisedBy", label: "Raised By" },
              { key: "reason", label: "Reason" },
              { key: "category", label: "Category", sortable: true },
              { key: "status", label: "Status", sortable: true },
              { key: "arbitratorName", label: "Arbitrator" },
              { key: "resolution", label: "Resolution" },
              { key: "createdAt", label: "Created", sortable: true },
            ],
          },
          {
            key: "documents",
            label: "Documents",
            apiBase: "/api/db/escrow-documents",
            columns: [
              { key: "id", label: "Doc ID" },
              { key: "documentType", label: "Type", sortable: true },
              { key: "fileName", label: "File Name" },
              { key: "fileSize", label: "Size", render: (v: any) => v ? `${(v / 1024).toFixed(0)} KB` : "—" },
              { key: "uploadedBy", label: "Uploaded By" },
              { key: "status", label: "Status", sortable: true },
              { key: "verifiedBy", label: "Verified By" },
              { key: "createdAt", label: "Uploaded", sortable: true },
            ],
          },
          {
            key: "fees",
            label: "Fees",
            apiBase: "/api/db/escrow-fees",
            columns: [
              { key: "id", label: "Fee ID" },
              { key: "escrowId", label: "Escrow" },
              { key: "feeType", label: "Type", sortable: true },
              { key: "amount", label: "Amount", sortable: true, render: (v: any) => `₦${Number(v).toLocaleString()}` },
              { key: "status", label: "Status" },
              { key: "ledgerRef", label: "Ledger Ref" },
              { key: "chargedAt", label: "Charged At", sortable: true },
            ],
          },
          {
            key: "interest",
            label: "Interest Accruals",
            apiBase: "/api/db/escrow-interest",
            columns: [
              { key: "id", label: "Accrual ID" },
              { key: "escrowId", label: "Escrow" },
              { key: "principalAmount", label: "Principal", render: (v: any) => `₦${Number(v).toLocaleString()}` },
              { key: "rate", label: "Rate %", render: (v: any) => `${v}%` },
              { key: "daysInPeriod", label: "Days" },
              { key: "interestAmount", label: "Interest", render: (v: any) => `₦${Number(v).toLocaleString()}` },
              { key: "cumulativeInterest", label: "Cumulative", render: (v: any) => `₦${Number(v).toLocaleString()}` },
              { key: "status", label: "Status" },
            ],
          },
          {
            key: "regulatory",
            label: "Regulatory Reports",
            apiBase: "/api/db/escrow-regulatory",
            columns: [
              { key: "id", label: "Report ID" },
              { key: "reportType", label: "Type", sortable: true },
              { key: "periodStart", label: "Period Start" },
              { key: "periodEnd", label: "Period End" },
              { key: "totalAccounts", label: "Accounts" },
              { key: "totalHeldValue", label: "Held Value", render: (v: any) => `₦${Number(v).toLocaleString()}` },
              { key: "status", label: "Status", sortable: true },
              { key: "filingReference", label: "Filing Ref" },
            ],
          },
          {
            key: "notifications",
            label: "Notifications",
            apiBase: "/api/db/customer-notifications",
            columns: [
              { key: "id", label: "ID" },
              { key: "escrowId", label: "Escrow" },
              { key: "type", label: "Type", sortable: true },
              { key: "channel", label: "Channel" },
              { key: "recipient", label: "Recipient" },
              { key: "subject", label: "Subject" },
              { key: "status", label: "Status" },
              { key: "sentAt", label: "Sent At", sortable: true },
            ],
          },
          {
            key: "audit",
            label: "Audit Log",
            apiBase: "/api/db/escrow-audit",
            columns: [
              { key: "id", label: "Audit ID" },
              { key: "escrowId", label: "Escrow" },
              { key: "action", label: "Action", sortable: true },
              { key: "actor", label: "Actor" },
              { key: "details", label: "Details" },
              { key: "kafkaTopic", label: "Kafka Topic" },
              { key: "timestamp", label: "Timestamp", sortable: true },
            ],
          },
        ],
      }}
    />
  );
}
