-- Rollback: initial schema
DROP TABLE IF EXISTS audit_trail CASCADE;
DROP TABLE IF EXISTS dlq_messages CASCADE;
DROP TABLE IF EXISTS feature_flags CASCADE;
DROP TABLE IF EXISTS event_store CASCADE;
DROP TABLE IF EXISTS ndpr_dsar CASCADE;
DROP TABLE IF EXISTS ndpr_consents CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;
DROP TABLE IF EXISTS users CASCADE;
