apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron-daily
  namespace: 54bank
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "0 2 * * *"
    - name: direction
      value: input
