apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: 54bank
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "localhost:9092"
    - name: consumerGroup
      value: "54bank-dapr"
    - name: authType
      value: "none"
