apiVersion: v1
kind: Service
metadata:
  name: {{ include "sanctions-screening-service.fullname" . }}
  labels:
    {{- include "sanctions-screening-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "sanctions-screening-service.selectorLabels" . | nindent 4 }}
