replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54link-dev-compliance-kyc-aml
  pullPolicy: IfNotPresent
  tag: "0.0.4"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54link
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9209
    - port: 9210
    - port: 9211
    - port: 9212
    - port: 9213
    - port: 9214
    - port: 9215
    - port: 9216
    - port: 9217
    - port: 9218
    - port: 9219
    - port: 9220
    - port: 9221
    - port: 9222
    - port: 9223
    - port: 9224
    - port: 9225
    - port: 9226
    - port: 9227
    - port: 9228
    - port: 9229
    - port: 9230
    - port: 9231
    - port: 9232
    - port: 9233
    - port: 9234
    - port: 9235
    - port: 9237
    - port: 9238
    - port: 9239
    - port: 9240
    - port: 9241
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    ephemeral-storage: 2Gi
    cpu: 500m
    memory: 1Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: compliance-kyc-aml
  appPort: 9211
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  DATABASE_URL: "postgresql://doadmin:AVNS_MSy6CW3EGXnA8wJgkLv@db-postgresql-nyc1-18193-do-user-10555812-0.e.db.ondigitalocean.com:25060/link_core_banking"
  DATABASE_URI: "postgresql://doadmin:AVNS_MSy6CW3EGXnA8wJgkLv@db-postgresql-nyc1-18193-do-user-10555812-0.e.db.ondigitalocean.com:25060/link_core_banking"
  DATABASE_POOL_SIZE: "3"
  DATABASE_MAX_OVERFLOW: "2"
  DATABASE_POOL_TIMEOUT: "30"
  DATABASE_POOL_RECYCLE: "1800"
  DB_HOST: db-postgresql-nyc1-18193-do-user-10555812-0.e.db.ondigitalocean.com
  DB_PORT: "25060"
  DB_NAME: link_core_banking
  DB_USER: doadmin
  DB_PASSWORD: AVNS_MSy6CW3EGXnA8wJgkLv
  REDIS_URL: redis-master.redis.svc.cluster.local:6379
  REDIS_ADDRESS: redis-master.redis.svc.cluster.local:6379
  REDIS_HOST: redis-master.redis.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_PASSWORD: 3phHSv7qbAuZLb2pi9FWED2X
  KAFKA_BROKERS: mojaloop-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  KAFKA_BOOTSTRAP_SERVERS: mojaloop-kafka-cluster-kafka-bootstrap.kafka.svc:9092
  KAFKA_SECURITY_PROTOCOL: PLAINTEXT
  KAFKA_SASL_MECHANISM: ""
  KAFKA_SASL_USERNAME: ""
  KAFKA_SASL_PASSWORD: ""
  FLUVIO_ENDPOINT: fluvio:9003
  FLUVIO_ADDR: fluvio:9003
  DAPR_URL: "http://localhost:3500"
  DAPR_HTTP_PORT: "3500"
  DAPR_PUBSUB: pubsub
  DAPR_PUBSUB_NAME: pubsub
  DAPR_PLACEMENT_ADDRESS: dapr-placement:50005
  KEYCLOAK_URL: https://keycloak.servers.upi.dev
  KEYCLOAK_BASE_URL: https://keycloak.servers.upi.dev
  KEYCLOAK_ADMIN_USERNAME: admin
  KEYCLOAK_ADMIN_PASSWORD: "0lQ09=4+Wcpi)DW"
  DEFAULT_KEYCLOAK_REALM: 54link
  AUTH_ENFORCER_URL: "http://auth-enforcer-rs.54link-dev.svc.cluster.local:8314"
  ALLOWED_ORIGINS: "*"
  PERMIFY_URL: http://permify.permify.svc.cluster.local:3476
  PERMIFY_HOST: permify.54link-dev.svc.cluster.local
  PERMIFY_PORT: "3476"
  TIGERBEETLE_ADDRESS: "10.233.107.191:3000,10.233.108.26:3000,10.233.108.25:3000"
  TIGERBEETLE_ADDRESSES: "10.233.107.191:3000,10.233.108.26:3000,10.233.108.25:3000"
  TIGERBEETLE_CLUSTER_ID: af786bfebbbab6fcb3acd4184e6fe4f4
  TB_ADDRESS: "10.233.107.191:3000,10.233.108.26:3000,10.233.108.25:3000"
  TB_CLUSTER_ID: "233240165285264747596733200182526600436"
  TEMPORAL_ADDRESS: temporal-frontend.temporal.svc:7233
  TEMPORAL_NAMESPACE: "54link-dev"
  APISIX_ADMIN_URL: http://apisix-admin.apisix.svc.cluster.local:9180
  OPENSEARCH_URL: https://shared-cluster-master.opensearch.svc.cluster.local:9200
  OPENSEARCH_USERNAME: admin
  OPENSEARCH_PASSWORD: "newwave@opensearch"
  OPENSEARCH_VERIFY_CERTS: "false"
  LAKEHOUSE_API_URL: http://data-intelligence.54link.svc.cluster.local:8000
  APP_HOST: "0.0.0.0"
  APP_PORT: "9209"
  LOG_PATH: "./logs"
  LOG_LEVEL: info
  LOG_SILENT: "false"
  PORT_BASE: "9209"
  SERVICE_GROUP: compliance-kyc-aml
  SERVICES: "address-verification-py,adverse-media-scanner-py,adverse-media-screening-py,agent-kyc-capture-go,aml-case-manager-go,aml-compliance-dashboard-py,aml-engine-rs,aml-risk-scoring-rs,aml-training-tracker-go,bvn-nin-verification-go,cbn-tiered-kyc-rs,corporate-doc-verification-py,efass-kyc-returns-py,goaml-integration-go,kyb-service,kyc-aml-screening-py,kyc-analytics-dashboard-py,kyc-data-quality-py,kyc-event-consumer-py,kyc-self-service-py,kyc-workflow-orchestration-py,multi-bureau-verification-go,pep-enhanced-dd-py,sanctions-batch-rescreener-rs,sanctions-engine-rs,sanctions-screening-rs,signature-verification-rs,telegram-kyc-bot-rs,ubo-service,video-kyc-py,watchlist-manager-rs"
