from .health import health_router
from .account import account_router
from .bank import bank_router
from .system import system_router
from .statements import statements_router
from .account_opening import opening_router
from .account_closure import closure_router
from .safe_deposit import safe_deposit_router
from .billing import billing_router
