"""Shared JWT validation for 54link-dev services.

Real signature verification — no warn-and-allow, no structural-only checks.

Resolution order:
1. If KEYCLOAK_JWKS_URL is set and PyJWT (with crypto extras) is installed,
   verify RS256/HS256 tokens against the Keycloak realm JWKS endpoint, e.g.
   https://<host>/realms/<realm>/protocol/openid-connect/certs
2. Else if JWT_SECRET is set, verify HS256 tokens using the stdlib
   (hmac/hashlib/base64) — no third-party dependency required.
3. Else FAIL CLOSED: return (None, "auth_not_configured").

Always validates: token structure, signature, alg allowlist, exp claim
(required), and iss when JWT_ISSUER is configured.

Usage:
    from shared.auth.jwt_validation import validate_jwt
    claims, err = validate_jwt(dict(self.headers))
    if err:
        ...  # 401

Standalone services that cannot import this package should inline the
stdlib HS256 verifier generated by scripts/fix-validate-jwt.py.
"""

import os
import time
import hmac
import base64
import hashlib
import json

KEYCLOAK_JWKS_URL = os.environ.get("KEYCLOAK_JWKS_URL", "")
JWT_SECRET = os.environ.get("JWT_SECRET", "")
JWT_ISSUER = os.environ.get("JWT_ISSUER", "")

try:
    import jwt  # PyJWT
    from jwt import PyJWKClient
    _PYJWT_AVAILABLE = True
except ImportError:
    _PYJWT_AVAILABLE = False

_jwks_client = None


def _b64url_decode(segment: str) -> bytes:
    segment += "=" * (-len(segment) % 4)
    return base64.urlsafe_b64decode(segment.encode())


def _get_jwks_client():
    global _jwks_client
    if _jwks_client is None:
        _jwks_client = PyJWKClient(KEYCLOAK_JWKS_URL, timeout=5)
    return _jwks_client


def _validate_claims(payload: dict):
    """Validate exp (required) and iss (when configured). Returns error or None."""
    exp = payload.get("exp")
    if exp is None:
        return "Token missing exp claim"
    try:
        if time.time() >= float(exp):
            return "Token expired"
    except (TypeError, ValueError):
        return "Invalid token expiry"
    if JWT_ISSUER and payload.get("iss") != JWT_ISSUER:
        return "Invalid token issuer"
    return None


def _verify_hs256_stdlib(token: str):
    """Stdlib HS256 verification. Returns (payload, None) or (None, reason)."""
    parts = token.split(".")
    if len(parts) != 3:
        return None, "Invalid token format"
    if not JWT_SECRET or JWT_SECRET.startswith("${"):
        return None, "auth_not_configured"
    try:
        header = json.loads(_b64url_decode(parts[0]))
        payload = json.loads(_b64url_decode(parts[1]))
        signature = _b64url_decode(parts[2])
    except Exception:
        return None, "Invalid token encoding"
    if header.get("alg") != "HS256":
        return None, "Unsupported token algorithm"
    expected = hmac.new(
        JWT_SECRET.encode(), (parts[0] + "." + parts[1]).encode(), hashlib.sha256
    ).digest()
    if not hmac.compare_digest(expected, signature):
        return None, "Invalid token signature"
    err = _validate_claims(payload)
    if err:
        return None, err
    return payload, None


def validate_jwt(headers):
    """Validate a Bearer JWT from a headers mapping.

    Returns (claims, None) on success or (None, reason) on failure.
    Fails closed: any token that cannot be cryptographically verified is
    rejected, and when neither KEYCLOAK_JWKS_URL nor JWT_SECRET is configured
    the result is (None, "auth_not_configured").
    """
    auth = headers.get("Authorization", headers.get("authorization", ""))
    if not auth.startswith("Bearer "):
        return None, "Missing Bearer token"
    token = auth[7:]
    parts = token.split(".")
    if len(parts) != 3:
        return None, "Invalid token format"

    # 1. Keycloak JWKS (RS256/HS256) via PyJWT when available.
    if KEYCLOAK_JWKS_URL:
        if _PYJWT_AVAILABLE:
            try:
                key = _get_jwks_client().get_signing_key_from_jwt(token).key
                decode_opts = {"require": ["exp"]}
                kwargs = {}
                if JWT_ISSUER:
                    kwargs["issuer"] = JWT_ISSUER
                else:
                    decode_opts["verify_iss"] = False
                claims = jwt.decode(
                    token, key, algorithms=["RS256", "HS256"],
                    options=decode_opts, **kwargs,
                )
                return claims, None
            except Exception as e:
                return None, f"Invalid token: {e}"
        # PyJWT unavailable — fall through to stdlib HS256 if configured.

    # 2. Stdlib HS256 with JWT_SECRET.
    if JWT_SECRET and not JWT_SECRET.startswith("${"):
        return _verify_hs256_stdlib(token)

    # 3. Fail closed.
    return None, "auth_not_configured"
