replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54link-dev-workflow-operations
  pullPolicy: IfNotPresent
  tag: "0.0.8"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54link
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9671
    - port: 9672
    - port: 9673
    - port: 9674
    - port: 9675
    - port: 9676
    - port: 9678
    - port: 9679
    - port: 9680
    - port: 9681
    - port: 9682
    - port: 9683
    - port: 9685
    - port: 9686
    - port: 9687
    - port: 9688
    - port: 9689
    - port: 9690
    - port: 9691
    - port: 9692
    - port: 9693
    - port: 9694
    - port: 9695
    - port: 9696
    - port: 9697
    - port: 9698
    - port: 9699
    - port: 9700
    - port: 9701
    - port: 9702
    - port: 9703
    - port: 9704
    - port: 9705
    - port: 9706
    - port: 9707
    - port: 9708
    - port: 9709
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    ephemeral-storage: 2Gi
    cpu: 500m
    memory: 1Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: workflow-operations
  appPort: 9697
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  APP_PORT: "9671"
  PORT_BASE: "9671"
  SERVICE_GROUP: workflow-operations
  SERVICES: "animal-id-traceability-rs,banking-domain-integration-go,banking-operations-pipeline-py,branch-manager-service,branch-operations-go,cac-realtime-api-go,core-banking-go,credit-bureau-rs,credit-facility-go,dispute-management-py,docling-service,document-management-py,document-service,erpnext-bridge-go,erpnext-integration-service,erpnext-sync-py,fixed-assets-go,immutable-audit-rs,inventory-py,ndpr-compliance-py,ocr-service,opensearch-indexer-py,opensearch-optimizer-py,pentest-orchestrator-go,platform-hardening-rs,platform-security-infra-go,secrets-rotation-rs,secrets-vault-go,security-audit-logger-py,security-hardening-go,session-security-rs,sql-parameterizer-rs,standing-charges-go,tax-reporting-py,teller-operations-go,typology-detector-rs,ubo-ownership-graph-rs,vault-integration-rs"
