replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54link-dev-infra-messaging
  pullPolicy: IfNotPresent
  tag: "0.0.1"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54link
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9415
    - port: 9416
    - port: 9417
    - port: 9418
    - port: 9419
    - port: 9420
    - port: 9421
    - port: 9422
    - port: 9423
    - port: 9424
    - port: 9425
    - port: 9426
    - port: 9427
    - port: 9428
    - port: 9429
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    ephemeral-storage: 2Gi
    cpu: 500m
    memory: 1Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: infra-messaging
  appPort: 9416
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  APP_PORT: "9415"
  PORT_BASE: "9415"
  SERVICE_GROUP: infra-messaging
  SERVICES: "billing-event-processor-py,event-bus-go,event-correlator-py,event-dedup-engine-rs,event-sourcing-go,event-streaming-go,fluvio-streams-rs,fluvio-wasm-transform-rs,kafka-batch-producer-rs,kafka-broker-go,kafka-consumer-optimizer-go,kafka-lakehouse-connector,kafka-schema-registry-go,kafka-streaming-go,stream-response-go"
