# ab-testing-py
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-ab-testing-py-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /ab-testing/*
      backends:
        - serviceName: platform-devops
          servicePort: 9508
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/ab-testing/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
