# address-verification-py
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-address-verification-py-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /address-verification/*
      backends:
        - serviceName: compliance-kyc-aml
          servicePort: 9209
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/address-verification/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
