# agent-customer-360-py
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-agent-customer-360-py-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /agent-customer-360/*
      backends:
        - serviceName: channels-agents
          servicePort: 9137
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/agent-customer-360/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
