# agent-kyc-capture-go
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-agent-kyc-capture-go-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /agent-kyc-capture/*
      backends:
        - serviceName: compliance-kyc-aml
          servicePort: 9212
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/agent-kyc-capture/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
