# approval-workflow-go
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-approval-workflow-go-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /approval-workflow/*
      backends:
        - serviceName: security-access
          servicePort: 9534
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/approval-workflow/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
