# batch-processing-py
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-batch-processing-py-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /batch-processing/*
      backends:
        - serviceName: workflow-batch
          servicePort: 9659
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/batch-processing/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
