# billing routes — served by billing-service (central billing engine)
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-billing-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-billing
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /billing/*
      backends:
        - serviceName: platform-tenant
          servicePort: 9523
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/billing/(.*)"
              - "/billing/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
    - name: rule-billing-event-processor
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /billing-event-processor/*
      backends:
        - serviceName: platform-tenant
          servicePort: 9523
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/billing-event-processor/(.*)"
              - "/billing-event-processor/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
