# biometric-auth-rs
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-biometric-auth-rs-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /biometric-auth/*
      backends:
        - serviceName: identity-auth
          servicePort: 9366
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/biometric-auth/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
