# bundle-splitter-py
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-bundle-splitter-py-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /bundle-splitter/*
      backends:
        - serviceName: platform-api
          servicePort: 9499
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/bundle-splitter/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
