# cbn-anchor-borrowers-go
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-cbn-anchor-borrowers-go-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /cbn-anchor-borrowers/*
      backends:
        - serviceName: compliance-regulatory
          servicePort: 9249
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/cbn-anchor-borrowers/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
