# cbn-compliance-checker-py
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-cbn-compliance-checker-py-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /cbn-compliance-checker/*
      backends:
        - serviceName: compliance-regulatory
          servicePort: 9250
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/cbn-compliance-checker/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
