# cbn-tiered-kyc-rs
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-cbn-tiered-kyc-rs-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /cbn-tiered-kyc/*
      backends:
        - serviceName: compliance-kyc-aml
          servicePort: 9220
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/cbn-tiered-kyc/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
