# commodity-price-intelligence-py
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-commodity-price-intelligence-py-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /commodity-price-intelligence/*
      backends:
        - serviceName: treasury-investments
          servicePort: 9643
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/commodity-price-intelligence/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
