apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-credit-service-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /credit/*
      backends:
        - serviceName: core-lending
          servicePort: 9315
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/credit/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
    - name: rule-2
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /banking-clearing-ops/*
      backends:
        - serviceName: core-lending
          servicePort: 9315
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/banking-clearing-ops/v1/(.*)"
              - "/v1/banking-clearing-ops/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
