# distroless-builder-py
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-distroless-builder-py-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /distroless-builder/*
      backends:
        - serviceName: security-waf
          servicePort: 9546
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/distroless-builder/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
