# document-intelligence-py
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-document-intelligence-py-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /document-intelligence/*
      backends:
        - serviceName: ai-data-pipeline
          servicePort: 9101
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/document-intelligence/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
