# exam-management-py
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-exam-management-py-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /exam-management/*
      backends:
        - serviceName: specialized-islamic
          servicePort: 9606
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/exam-management/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
