# express-rate-limiter-rs
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-express-rate-limiter-rs-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /express-rate-limiter/*
      backends:
        - serviceName: infra-network
          servicePort: 9437
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/express-rate-limiter/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
