# ifrs9-ecl-engine-rs
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-ifrs9-ecl-engine-rs-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /ifrs9-ecl-engine/*
      backends:
        - serviceName: compliance-regulatory
          servicePort: 9258
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/ifrs9-ecl-engine/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
