# ip-allowlist-rs
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-ip-allowlist-rs-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /ip-allowlist/*
      backends:
        - serviceName: security-waf
          servicePort: 9552
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/ip-allowlist/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
