# jwt-validator-rs
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-jwt-validator-rs-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /jwt-validator/*
      backends:
        - serviceName: identity-auth
          servicePort: 9374
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/jwt-validator/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
