# kpi-threshold-monitor-rs
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-kpi-threshold-monitor-rs-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /kpi-threshold-monitor/*
      backends:
        - serviceName: infra-observability
          servicePort: 9456
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/kpi-threshold-monitor/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
