# lakehouse-etl-py
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-lakehouse-etl-py-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /lakehouse-etl/*
      backends:
        - serviceName: ai-data-pipeline
          servicePort: 9102
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/lakehouse-etl/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
