# multi-peril-crop-insurance-rs
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-multi-peril-crop-insurance-rs-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /multi-peril-crop-insurance/*
      backends:
        - serviceName: specialized-agri
          servicePort: 9584
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/multi-peril-crop-insurance/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
