# open-banking-baas-go
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-open-banking-baas-go-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /open-banking-baas/*
      backends:
        - serviceName: channels-mobile-web
          servicePort: 9173
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/open-banking-baas/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
