# opensearch-analytics-py
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-opensearch-analytics-py-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /opensearch-analytics/*
      backends:
        - serviceName: workflow-reporting
          servicePort: 9733
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/opensearch-analytics/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
