# post-harvest-loss-tracker-go
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-post-harvest-loss-tracker-go-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /post-harvest-loss-tracker/*
      backends:
        - serviceName: specialized-agri
          servicePort: 9587
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/post-harvest-loss-tracker/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
