# tenant-web-app
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-tenant-web-app-route
  namespace: 54link-dev
spec:
  ingressClassName:  apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - pup.54link-dev.upi.dev
        paths:
          - /*
      backends:
        - serviceName: pup-web-app
          servicePort: 80
      plugins:
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"