# sw-api-cache-go
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-sw-api-cache-go-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /sw-api-cache/*
      backends:
        - serviceName: infra-caching
          servicePort: 9397
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/sw-api-cache/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
