# swift-iso20022-rs
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-swift-iso20022-rs-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /swift-iso20022/*
      backends:
        - serviceName: trade-fx
          servicePort: 9620
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/swift-iso20022/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
