# telegram-banking-commands-rs
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-telegram-banking-commands-rs-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /telegram-banking-commands/*
      backends:
        - serviceName: channels-messaging
          servicePort: 9156
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/telegram-banking-commands/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
