# tenant-provisioning-go
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-tenant-provisioning-go-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /tenant-provisioning/*
      backends:
        - serviceName: compliance-risk
          servicePort: 9274
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/tenant-provisioning/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
