# trade-finance-gl-go
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-trade-finance-gl-go-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /trade-finance-gl/*
      backends:
        - serviceName: trade-fx
          servicePort: 9622
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/trade-finance-gl/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
