# ussd-transaction-engine-rs
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-ussd-transaction-engine-rs-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /ussd-transaction-engine/*
      backends:
        - serviceName: channels-voice
          servicePort: 9186
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/ussd-transaction-engine/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
