# vault-integration-rs
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-vault-integration-rs-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /vault-integration/*
      backends:
        - serviceName: workflow-operations
          servicePort: 9709
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/vault-integration/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
