# voice-asr-nigerian-py
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-voice-asr-nigerian-py-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /voice-asr-nigerian/*
      backends:
        - serviceName: channels-voice
          servicePort: 9188
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/voice-asr-nigerian/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
