# voice-agent-escalation-go
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-voice-agent-escalation-go-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /voice-agent-escalation/*
      backends:
        - serviceName: channels-voice
          servicePort: 9187
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/voice-agent-escalation/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
