# whatsapp-document-service-rs
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-whatsapp-document-service-rs-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /whatsapp-document/*
      backends:
        - serviceName: channels-messaging
          servicePort: 9164
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/whatsapp-document/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
