# whatsapp-banking-flows-rs
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-whatsapp-banking-flows-rs-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /whatsapp-banking-flows/*
      backends:
        - serviceName: channels-messaging
          servicePort: 9161
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/whatsapp-banking-flows/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
