# white-label-engine-go
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54link-dev-white-label-engine-go-route
  namespace: 54link-dev
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54link-dev.upi.dev
        paths:
          - /white-label-engine/*
      backends:
        - serviceName: platform-tenant
          servicePort: 9531
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/white-label-engine/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
