/**
 * Object storage helpers for 54Bank platform.
 * Uses standard S3-compatible object storage (AWS S3, MinIO, Cloudflare R2, etc.)
 * via pre-signed URLs generated by the AWS SDK v3.
 *
 * Configuration (environment variables):
 *   S3_BUCKET_NAME       — required: bucket name
 *   S3_REGION            — required: AWS region (e.g. us-east-1)
 *   AWS_ACCESS_KEY_ID    — required: access key
 *   AWS_SECRET_ACCESS_KEY — required: secret key
 *   S3_ENDPOINT          — optional: custom endpoint for MinIO/R2 (e.g. http://minio:9000)
 *   S3_PUBLIC_BASE_URL   — optional: CDN/public base URL for direct object access
 *
 * Falls back to local filesystem storage when S3 is not configured (development mode).
 */
import { ENV } from "./_core/env";
import path from "path";
import fs from "fs/promises";
import os from "os";

// ─── Types ────────────────────────────────────────────────────────────────────

type StorageResult = { key: string; url: string };

// ─── S3 Client (lazy-loaded to avoid hard dependency) ─────────────────────────

let s3Client: any = null;
let S3Commands: any = null;

async function getS3Client() {
  if (s3Client) return { client: s3Client, commands: S3Commands };

  const bucket = process.env.S3_BUCKET_NAME;
  const region = process.env.S3_REGION ?? "us-east-1";
  const accessKeyId = process.env.AWS_ACCESS_KEY_ID;
  const secretAccessKey = process.env.AWS_SECRET_ACCESS_KEY;
  const endpoint = process.env.S3_ENDPOINT;

  if (!bucket || !accessKeyId || !secretAccessKey) {
    return null; // Fall back to local storage
  }

  try {
    const { S3Client } = await import("@aws-sdk/client-s3");
    const { PutObjectCommand, GetObjectCommand } = await import("@aws-sdk/client-s3");
    const { getSignedUrl } = await import("@aws-sdk/s3-request-presigner");

    s3Client = new S3Client({
      region,
      credentials: { accessKeyId, secretAccessKey },
      ...(endpoint ? { endpoint, forcePathStyle: true } : {}),
    });

    S3Commands = { PutObjectCommand, GetObjectCommand, getSignedUrl, bucket };
    return { client: s3Client, commands: S3Commands };
  } catch {
    console.warn("[Storage] @aws-sdk/client-s3 not installed — falling back to local storage");
    return null;
  }
}

// ─── Local Filesystem Fallback (development only) ─────────────────────────────

const LOCAL_STORAGE_DIR = path.join(os.tmpdir(), "54bank-storage");

async function ensureLocalDir(): Promise<void> {
  await fs.mkdir(LOCAL_STORAGE_DIR, { recursive: true });
}

function appendHashSuffix(relKey: string): string {
  const hash = crypto.randomUUID().replace(/-/g, "").slice(0, 8);
  const segmentStart = relKey.lastIndexOf("/");
  const lastDot = relKey.lastIndexOf(".");
  if (lastDot === -1 || lastDot <= segmentStart) return `${relKey}_${hash}`;
  return `${relKey.slice(0, lastDot)}_${hash}${relKey.slice(lastDot)}`;
}

function normalizeKey(relKey: string): string {
  return relKey.replace(/^\/+/, "");
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Upload a file to object storage.
 * Returns the storage key and a publicly accessible URL.
 */
export async function storagePut(
  relKey: string,
  data: Buffer | Uint8Array | string,
  contentType = "application/octet-stream"
): Promise<StorageResult> {
  const key = appendHashSuffix(normalizeKey(relKey));
  const s3 = await getS3Client();

  if (s3) {
    // S3-compatible upload
    const { client, commands } = s3;
    const body = typeof data === "string" ? Buffer.from(data, "utf-8") : Buffer.from(data);
    await client.send(
      new commands.PutObjectCommand({
        Bucket: commands.bucket,
        Key: key,
        Body: body,
        ContentType: contentType,
      })
    );

    const publicBase = process.env.S3_PUBLIC_BASE_URL;
    const url = publicBase
      ? `${publicBase.replace(/\/$/, "")}/${key}`
      : await commands.getSignedUrl(
          client,
          new commands.GetObjectCommand({ Bucket: commands.bucket, Key: key }),
          { expiresIn: 3600 }
        );

    return { key, url };
  }

  // Local filesystem fallback
  if (ENV.isProduction) {
    throw new Error(
      "Object storage is not configured. Set S3_BUCKET_NAME, S3_REGION, AWS_ACCESS_KEY_ID, and AWS_SECRET_ACCESS_KEY."
    );
  }

  await ensureLocalDir();
  const filePath = path.join(LOCAL_STORAGE_DIR, key.replace(/\//g, "_"));
  const buffer = typeof data === "string" ? Buffer.from(data, "utf-8") : Buffer.from(data);
  await fs.writeFile(filePath, buffer);
  const url = `file://${filePath}`;
  console.warn(`[Storage] Local fallback: saved to ${filePath}`);
  return { key, url };
}

/**
 * Get a pre-signed download URL for a stored object.
 */
export async function storageGet(relKey: string): Promise<StorageResult> {
  const key = normalizeKey(relKey);
  const s3 = await getS3Client();

  if (s3) {
    const { client, commands } = s3;
    const publicBase = process.env.S3_PUBLIC_BASE_URL;
    const url = publicBase
      ? `${publicBase.replace(/\/$/, "")}/${key}`
      : await commands.getSignedUrl(
          client,
          new commands.GetObjectCommand({ Bucket: commands.bucket, Key: key }),
          { expiresIn: 3600 }
        );
    return { key, url };
  }

  // Local filesystem fallback
  const filePath = path.join(LOCAL_STORAGE_DIR, key.replace(/\//g, "_"));
  return { key, url: `file://${filePath}` };
}
