replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54link-dev-mojaloop-connector
  pullPolicy: IfNotPresent
  tag: "0.0.3"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54link
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9489
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    ephemeral-storage: 2Gi
    cpu: 500m
    memory: 1Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: mojaloop-connector
  appPort: 9489
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  TEMPORAL_TASK_QUEUE: "mojaloop-connector"
  CORE_BANKING_CONNECT_DAPR_ID: "core-payments"
  TENANT_NAME: "bpmgd"
  ACCOUNT_LOOKUP_SERVICE: "http://mojaloop-account-lookup-service.mojaloop.svc.cluster.local"
  QUOTES_SERVICE: "http://mojaloop-quoting-service.mojaloop.svc.cluster.local"
  TRANSFERS_SERVICE: "http://mojaloop-ml-api-adapter-service.mojaloop.svc.cluster.local"
  APP_PORT: "9489"
  PORT_BASE: "9489"
  SERVICE_GROUP: mojaloop-connector
  SERVICES: "mojaloop-connector"
