replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54link-dev-erp-integration
  pullPolicy: IfNotPresent
  tag: "0.0.3"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54link
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9750
    - port: 9751
    - port: 9752
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    ephemeral-storage: 2Gi
    cpu: 500m
    memory: 1Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: erp-integration
  appPort: 9751
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  APP_PORT: "9750"
  PORT_BASE: "9750"
  PORT: "9751"
  SERVICE_GROUP: erp-integration
  SERVICES: "erpnext-bridge-go,erpnext-integration-service,erpnext-sync-py"
