replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54link-dev-safe-deposit-go
  pullPolicy: IfNotPresent
  tag: "0.0.10"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54link
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9423
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    ephemeral-storage: 1Gi
    cpu: 300m
    memory: 512Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: safe-deposit-go
  appPort: 9423
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  APP_PORT: "9423"
  PORT: "9423"
  PORT_BASE: "9423"
  SERVICE_GROUP: safe-deposit-go
  SERVICES: "safe-deposit-go"
