{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "beneficial-ownership-go.serviceAccountName" . }}
  labels:
    {{- include "beneficial-ownership-go.labels" . | nindent 4 }}
{{- end }}
