-- Rollback: 001_create_whatsapp_payment_integration_tables
BEGIN;
DROP TRIGGER IF EXISTS trg_whatsapp_payment_integration_updated ON whatsapp_payment_integration_records;
DROP FUNCTION IF EXISTS update_whatsapp_payment_integration_timestamp();
DROP FUNCTION IF EXISTS cleanup_whatsapp_payment_integration_idempotency();
DROP POLICY IF EXISTS whatsapp_payment_integration_tenant_isolation ON whatsapp_payment_integration_records;
DROP TABLE IF EXISTS whatsapp_payment_integration_idempotency;
DROP TABLE IF EXISTS whatsapp_payment_integration_audit;
DROP TABLE IF EXISTS whatsapp_payment_integration_records;
COMMIT;
