-- Rollback: 001_create_banking_operations_pipeline_tables
BEGIN;
DROP TRIGGER IF EXISTS trg_banking_operations_pipeline_updated ON banking_operations_pipeline_records;
DROP FUNCTION IF EXISTS update_banking_operations_pipeline_timestamp();
DROP FUNCTION IF EXISTS cleanup_banking_operations_pipeline_idempotency();
DROP POLICY IF EXISTS banking_operations_pipeline_tenant_isolation ON banking_operations_pipeline_records;
DROP TABLE IF EXISTS banking_operations_pipeline_idempotency;
DROP TABLE IF EXISTS banking_operations_pipeline_audit;
DROP TABLE IF EXISTS banking_operations_pipeline_records;
COMMIT;
