apiVersion: v1
kind: Secret
metadata:
  name: business-service-secrets
  namespace: banking-platform
type: Opaque
stringData:
  DATABASE_URI: "postgresql://banking:CHANGE_ME@postgres.banking-platform.svc.cluster.local:5432/banking54"
  KEYCLOAK_URL: "https://keycloak.banking-platform.svc.cluster.local:8443"
  KEYCLOAK_CLIENT_SECRET: "CHANGE_ME"
  PERMIFY_HOST: "permify.banking-platform.svc.cluster.local"
  KAFKA_BROKERS: "kafka-cluster.kafka.svc.cluster.local:9092"
