{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tax-reporting-py.serviceAccountName" . }}
  labels:
    {{- include "tax-reporting-py.labels" . | nindent 4 }}
{{- end }}
