{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bulk-payments-rs.serviceAccountName" . }}
  labels:
    {{- include "bulk-payments-rs.labels" . | nindent 4 }}
{{- end }}
