replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54link-dev-specialized-engagement
  pullPolicy: IfNotPresent
  tag: "0.0.3"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54link
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9593
    - port: 9594
    - port: 9595
    - port: 9596
    - port: 9597
    - port: 9598
    - port: 9599
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    ephemeral-storage: 2Gi
    cpu: 500m
    memory: 1Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: specialized-engagement
  appPort: 9597
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  APP_PORT: "9593"
  PORT_BASE: "9593"
  SERVICE_GROUP: specialized-engagement
  SERVICES: "component-memoizer-py,gamification-service,growth-features-go,optimistic-ui-engine-go,skeleton-loading-rs,sorted-set-ranking-go,virtual-scroll-engine-rs"
