import type { Express } from "express";

interface ChannelService {
  path: string;
  port: number;
  topic: string;
  name: string;
}

const CHANNEL_SERVICES: ChannelService[] = [
  { path: "voice-banking-gateway", port: 8629, topic: "voice_banking_gateway", name: "voice-banking-gateway-go" },
  { path: "voice-tts-nigerian", port: 8630, topic: "voice_tts_nigerian", name: "voice-tts-nigerian-ru" },
  { path: "voice-asr-nigerian", port: 8631, topic: "voice_asr_nigerian", name: "voice-asr-nigerian-py" },
  { path: "voice-nlu-banking", port: 8632, topic: "voice_nlu_banking", name: "voice-nlu-banking-py" },
  { path: "voice-biometric-auth", port: 8633, topic: "voice_biometric_auth", name: "voice-biometric-auth-ru" },
  { path: "voice-ivr-menu", port: 8634, topic: "voice_ivr_menu", name: "voice-ivr-menu-go" },
  { path: "voice-call-analytics", port: 8635, topic: "voice_call_analytics", name: "voice-call-analytics-py" },
  { path: "voice-agent-escalation", port: 8636, topic: "voice_agent_escalation", name: "voice-agent-escalation-go" },
  { path: "telegram-bot-gateway", port: 8637, topic: "telegram_bot_gateway", name: "telegram-bot-gateway-go" },
  { path: "telegram-banking-commands", port: 8638, topic: "telegram_banking_commands", name: "telegram-banking-commands-ru" },
  { path: "telegram-notification", port: 8639, topic: "telegram_notification", name: "telegram-notification-py" },
  { path: "telegram-mini-app", port: 8640, topic: "telegram_mini_app", name: "telegram-mini-app-go" },
  { path: "telegram-kyc-bot", port: 8641, topic: "telegram_kyc_bot", name: "telegram-kyc-bot-ru" },
  { path: "whatsapp-business-gateway", port: 8642, topic: "whatsapp_business_gateway", name: "whatsapp-business-gateway-go" },
  { path: "whatsapp-banking-flows", port: 8643, topic: "whatsapp_banking_flows", name: "whatsapp-banking-flows-ru" },
  { path: "whatsapp-payment-integration", port: 8644, topic: "whatsapp_payment_integration", name: "whatsapp-payment-integration-go" },
  { path: "whatsapp-notification", port: 8645, topic: "whatsapp_notification", name: "whatsapp-notification-py" },
  { path: "whatsapp-document-service", port: 8646, topic: "whatsapp_document_service", name: "whatsapp-document-service-ru" },
  { path: "ussd-banking-gateway", port: 8647, topic: "ussd_banking_gateway", name: "ussd-banking-gateway-go" },
  { path: "ussd-transaction-engine", port: 8648, topic: "ussd_transaction_engine", name: "ussd-transaction-engine-ru" },
  { path: "ussd-multilingual", port: 8649, topic: "ussd_multilingual", name: "ussd-multilingual-py" },
  { path: "ussd-sim-toolkit", port: 8650, topic: "ussd_sim_toolkit", name: "ussd-sim-toolkit-go" },
  { path: "sms-banking-gateway", port: 8651, topic: "sms_banking_gateway", name: "sms-banking-gateway-go" },
  { path: "sms-otp-service", port: 8652, topic: "sms_otp_service", name: "sms-otp-service-ru" },
  { path: "sms-alert-notification", port: 8653, topic: "sms_alert_notification", name: "sms-alert-notification-py" },
];

const SEED_FALLBACK: Record<string, unknown[]> = {
  voice_banking_gateway: [{"id":"VBG-001","name":"IVR Main Menu","category":"IVR","description":"Main voice banking menu \u2014 English, Hausa, Yoruba, Igbo, Pidgin","status":"active","language":"en","sessions":12845,"avgDuration":"2m 34s","callType":"inbound"},{"id":"VBG-002","name":"Balance Inquiry Flow","category":"IVR","description":"Account balance check via voice DTMF input","status":"active","language":"en","sessions":8920,"avgDuration":"1m 12s","callType":"inbound"},{"id":"VBG-003","name":"Transfer Flow","category":"IVR","description":"Fund transfer via voice with OTP confirmation","status":"active","language":"ha","sessions":5634,"avgDuration":"3m 45s","callType":"inbound"},{"id":"VBG-004","name":"Bill Payment Flow","category":"IVR","description":"Utility bill payment via voice banking","status":"active","language":"yo","sessions":3210,"avgDuration":"2m 18s","callType":"inbound"},{"id":"VBG-005","name":"Card Block Request","category":"IVR","description":"Emergency card blocking via voice","status":"active","language":"en","sessions":890,"avgDuration":"1m 45s","callType":"inbound"},{"id":"VBG-006","name":"Loan Status Check","category":"IVR","description":"Check loan application and repayment status","status":"active","language":"ig","sessions":2340,"avgDuration":"1m 55s","callType":"inbound"}],
  voice_tts_nigerian: [{"id":"TTS-001","name":"Adebayo (Male Yoruba)","category":"Voice","description":"Deep baritone male voice \u2014 Yoruba-accented English","status":"active","language":"yo-en","sampleRate":"22050 Hz","gender":"male","provider":"54Bank-NLP"},{"id":"TTS-002","name":"Ngozi (Female Igbo)","category":"Voice","description":"Soprano female voice \u2014 Igbo-accented English","status":"active","language":"ig-en","sampleRate":"22050 Hz","gender":"female","provider":"54Bank-NLP"},{"id":"TTS-003","name":"Aminu (Male Hausa)","category":"Voice","description":"Warm baritone male voice \u2014 Hausa-accented English","status":"active","language":"ha-en","sampleRate":"22050 Hz","gender":"male","provider":"54Bank-NLP"},{"id":"TTS-004","name":"Aisha (Female Hausa)","category":"Voice","description":"Clear mezzo female voice \u2014 Hausa accent","status":"active","language":"ha","sampleRate":"22050 Hz","gender":"female","provider":"54Bank-NLP"},{"id":"TTS-005","name":"Chidi (Male Pidgin)","category":"Voice","description":"Friendly male voice \u2014 Nigerian Pidgin","status":"active","language":"pcm","sampleRate":"22050 Hz","gender":"male","provider":"54Bank-NLP"}],
  voice_asr_nigerian: [{"id":"ASR-001","name":"English (Nigerian)","category":"ASR","description":"Nigerian English recognition \u2014 Lagos, Abuja, PH accent training","status":"active","accuracy":"94.2%","language":"en-NG","model":"wav2vec2-ng-en"},{"id":"ASR-002","name":"Hausa","category":"ASR","description":"Hausa speech recognition \u2014 Kano, Kaduna, Sokoto dialects","status":"active","accuracy":"91.8%","language":"ha","model":"wav2vec2-ng-ha"},{"id":"ASR-003","name":"Yoruba","category":"ASR","description":"Yoruba speech recognition \u2014 Lagos, Ibadan, Abeokuta dialects","status":"active","accuracy":"90.5%","language":"yo","model":"wav2vec2-ng-yo"},{"id":"ASR-004","name":"Igbo","category":"ASR","description":"Igbo speech recognition \u2014 Owerri, Enugu, Onitsha dialects","status":"active","accuracy":"89.3%","language":"ig","model":"wav2vec2-ng-ig"},{"id":"ASR-005","name":"Pidgin","category":"ASR","description":"Nigerian Pidgin recognition \u2014 market & informal settings","status":"active","accuracy":"87.6%","language":"pcm","model":"wav2vec2-ng-pcm"}],
  voice_nlu_banking: [{"id":"NLU-001","name":"Balance Intent","category":"Intent","description":"'How much dey my account?' \u2192 balance_check","status":"active","confidence":"0.96","examples":42,"language":"multi"},{"id":"NLU-002","name":"Transfer Intent","category":"Intent","description":"'Send money to Emeka' \u2192 fund_transfer","status":"active","confidence":"0.94","examples":38,"language":"multi"},{"id":"NLU-003","name":"Bill Pay Intent","category":"Intent","description":"'Pay my DSTV' \u2192 bill_payment","status":"active","confidence":"0.93","examples":35,"language":"multi"},{"id":"NLU-004","name":"Card Block Intent","category":"Intent","description":"'Block my card now!' \u2192 card_block_emergency","status":"active","confidence":"0.97","examples":28,"language":"multi"},{"id":"NLU-005","name":"Loan Application","category":"Intent","description":"'I wan borrow money' \u2192 loan_apply","status":"active","confidence":"0.91","examples":31,"language":"multi"}],
  voice_biometric_auth: [{"id":"BIO-001","name":"Enrollment \u2014 Adebola Ogundimu","category":"Voiceprint","description":"3-phrase voiceprint enrolled \u2014 anti-spoofing verified","status":"verified","enrollDate":"2026-04-15","confidence":"0.98","phrases":3},{"id":"BIO-002","name":"Enrollment \u2014 Chukwuma Eze","category":"Voiceprint","description":"3-phrase voiceprint enrolled \u2014 liveness check passed","status":"verified","enrollDate":"2026-04-18","confidence":"0.96","phrases":3},{"id":"BIO-003","name":"Enrollment \u2014 Hauwa Ibrahim","category":"Voiceprint","description":"3-phrase voiceprint enrolled \u2014 noise-robust model","status":"verified","enrollDate":"2026-04-20","confidence":"0.95","phrases":3},{"id":"BIO-004","name":"Enrollment \u2014 Oluwaseun Akinwale","category":"Voiceprint","description":"Re-enrollment after voice change \u2014 updated model","status":"pending","enrollDate":"2026-05-01","confidence":"0.88","phrases":2}],
  voice_ivr_menu: [{"id":"IVR-001","name":"Main Menu","category":"Menu","description":"Welcome \u2192 Language Select \u2192 Service Menu (1-9)","status":"active","depth":0,"options":9,"language":"multi"},{"id":"IVR-002","name":"Account Services","category":"Menu","description":"Balance, Mini-statement, Account Info, Block Card","status":"active","depth":1,"options":4,"language":"multi"},{"id":"IVR-003","name":"Transfer Services","category":"Menu","description":"Own Account, Other Bank, Mobile Money, International","status":"active","depth":1,"options":4,"language":"multi"},{"id":"IVR-004","name":"Bill Payments","category":"Menu","description":"Electricity, Water, Cable TV, Airtime, Internet","status":"active","depth":1,"options":5,"language":"multi"},{"id":"IVR-005","name":"Loan Services","category":"Menu","description":"Apply, Check Status, Repayment, Calculator","status":"active","depth":1,"options":4,"language":"multi"}],
  voice_call_analytics: [{"id":"VCA-001","name":"Daily Call Volume","category":"Analytics","description":"12,845 calls processed \u2014 98.2% completion rate","status":"active","metric":"call_volume","value":"12,845","period":"daily"},{"id":"VCA-002","name":"Avg Hold Time","category":"Analytics","description":"Average hold time 45 seconds \u2014 target < 60s","status":"active","metric":"avg_hold_time","value":"45s","period":"daily"},{"id":"VCA-003","name":"Sentiment Score","category":"Analytics","description":"Customer satisfaction 4.2/5.0 from post-call survey","status":"active","metric":"csat","value":"4.2/5.0","period":"weekly"},{"id":"VCA-004","name":"Language Distribution","category":"Analytics","description":"English 52%, Hausa 22%, Yoruba 15%, Igbo 8%, Pidgin 3%","status":"active","metric":"language_dist","value":"52/22/15/8/3","period":"monthly"},{"id":"VCA-005","name":"Peak Hour Analysis","category":"Analytics","description":"Peak: 10am-12pm (28% of daily volume)","status":"active","metric":"peak_hour","value":"10:00-12:00","period":"daily"}],
  voice_agent_escalation: [{"id":"ESC-001","name":"Fraud Alert Escalation","category":"Escalation","description":"Suspected fraud \u2014 auto-escalated to fraud desk","status":"active","priority":"critical","avgWait":"15s","resolution":"2m"},{"id":"ESC-002","name":"Complex Transaction","category":"Escalation","description":"Transaction above \u20a65M \u2014 requires agent verification","status":"active","priority":"high","avgWait":"30s","resolution":"5m"},{"id":"ESC-003","name":"Complaint Handling","category":"Escalation","description":"Customer complaint \u2014 routed to complaint resolution team","status":"active","priority":"medium","avgWait":"45s","resolution":"8m"},{"id":"ESC-004","name":"Technical Issue","category":"Escalation","description":"System error during transaction \u2014 technical support","status":"active","priority":"high","avgWait":"20s","resolution":"3m"}],
  telegram_bot_gateway: [{"id":"TBG-001","name":"54Bank_Bot","category":"Bot","description":"Main Telegram banking bot \u2014 125,000 subscribers","status":"active","subscribers":"125,000","commands":12,"webhook":"active"},{"id":"TBG-002","name":"54Bank_Alerts","category":"Bot","description":"Transaction alert bot \u2014 real-time notifications","status":"active","subscribers":"98,500","commands":5,"webhook":"active"},{"id":"TBG-003","name":"54Bank_Support","category":"Bot","description":"Customer support bot \u2014 AI-powered responses","status":"active","subscribers":"45,200","commands":8,"webhook":"active"},{"id":"TBG-004","name":"54Bank_Business","category":"Bot","description":"Business banking bot \u2014 corporate features","status":"active","subscribers":"12,800","commands":10,"webhook":"active"}],
  telegram_banking_commands: [{"id":"CMD-001","name":"/balance","category":"Command","description":"Check account balance \u2014 inline keyboard with account selector","status":"active","usage":"daily","avgResponseMs":"120"},{"id":"CMD-002","name":"/transfer","category":"Command","description":"Initiate fund transfer \u2014 conversational flow with OTP","status":"active","usage":"daily","avgResponseMs":"200"},{"id":"CMD-003","name":"/history","category":"Command","description":"Transaction history \u2014 last 10 transactions with pagination","status":"active","usage":"daily","avgResponseMs":"150"},{"id":"CMD-004","name":"/airtime","category":"Command","description":"Buy airtime \u2014 MTN, Glo, Airtel, 9mobile","status":"active","usage":"daily","avgResponseMs":"180"},{"id":"CMD-005","name":"/exchange_rate","category":"Command","description":"Live exchange rates \u2014 USD, EUR, GBP vs NGN","status":"active","usage":"hourly","avgResponseMs":"100"}],
  telegram_notification: [{"id":"TNT-001","name":"Credit Alert","category":"Notification","description":"Real-time credit notification via Telegram","status":"active","template":"credit_alert_v2","deliveryRate":"99.2%"},{"id":"TNT-002","name":"Debit Alert","category":"Notification","description":"Real-time debit notification via Telegram","status":"active","template":"debit_alert_v2","deliveryRate":"99.1%"},{"id":"TNT-003","name":"Loan Reminder","category":"Notification","description":"Loan repayment reminder \u2014 3 days before due date","status":"active","template":"loan_reminder_v1","deliveryRate":"98.5%"},{"id":"TNT-004","name":"Fraud Alert","category":"Notification","description":"Suspicious activity alert \u2014 immediate delivery","status":"active","template":"fraud_alert_v1","deliveryRate":"99.8%"}],
  telegram_mini_app: [{"id":"TMA-001","name":"Account Dashboard","category":"MiniApp","description":"Rich account overview with charts and quick actions","status":"active","users":"32,500","framework":"React"},{"id":"TMA-002","name":"QR Payment","category":"MiniApp","description":"Scan-to-pay QR code reader and generator","status":"active","users":"18,200","framework":"React"},{"id":"TMA-003","name":"Budget Tracker","category":"MiniApp","description":"Monthly budget tracking with spending categories","status":"active","users":"12,400","framework":"React"}],
  telegram_kyc_bot: [{"id":"KYC-001","name":"BVN Verification","category":"KYC","description":"Bank Verification Number check via Telegram chat","status":"active","verifications":"8,450","avgTime":"2m"},{"id":"KYC-002","name":"NIN Verification","category":"KYC","description":"National ID Number verification with NIMC API","status":"active","verifications":"6,200","avgTime":"3m"},{"id":"KYC-003","name":"Address Verification","category":"KYC","description":"Utility bill upload for address proof","status":"active","verifications":"4,100","avgTime":"5m"},{"id":"KYC-004","name":"Selfie Verification","category":"KYC","description":"Liveness check with photo ID matching","status":"active","verifications":"3,800","avgTime":"1m"}],
  whatsapp_business_gateway: [{"id":"WAG-001","name":"54Bank Business","category":"Gateway","description":"WhatsApp Business API \u2014 Cloud API integration","status":"active","monthlyMessages":"2.4M","phoneNumber":"+234-800-54-BANK","tier":"unlimited"},{"id":"WAG-002","name":"54Bank Support","category":"Gateway","description":"Customer support WhatsApp channel","status":"active","monthlyMessages":"890K","phoneNumber":"+234-800-54-HELP","tier":"standard"},{"id":"WAG-003","name":"54Bank Alerts","category":"Gateway","description":"Transaction alert delivery channel","status":"active","monthlyMessages":"4.2M","phoneNumber":"+234-800-54-ALRT","tier":"unlimited"}],
  whatsapp_banking_flows: [{"id":"WBF-001","name":"Balance Check Flow","category":"Flow","description":"Conversational balance inquiry with account selection","status":"active","completionRate":"94%","steps":3},{"id":"WBF-002","name":"Transfer Flow","category":"Flow","description":"Money transfer with beneficiary lookup and OTP","status":"active","completionRate":"88%","steps":5},{"id":"WBF-003","name":"Airtime Purchase","category":"Flow","description":"Buy airtime for self or others \u2014 all networks","status":"active","completionRate":"96%","steps":3},{"id":"WBF-004","name":"Account Opening","category":"Flow","description":"Open savings account via WhatsApp \u2014 BVN required","status":"active","completionRate":"72%","steps":8},{"id":"WBF-005","name":"Loan Application","category":"Flow","description":"Apply for personal loan \u2014 income verification","status":"active","completionRate":"65%","steps":7}],
  whatsapp_payment_integration: [{"id":"WPI-001","name":"P2P Transfer","category":"Payment","description":"Person-to-person WhatsApp payment \u2014 instant settlement","status":"active","dailyVolume":"\u20a6245M","txnCount":"18,500"},{"id":"WPI-002","name":"QR Pay","category":"Payment","description":"Scan WhatsApp QR code for merchant payments","status":"active","dailyVolume":"\u20a689M","txnCount":"12,200"},{"id":"WPI-003","name":"Bill Split","category":"Payment","description":"Split bill among WhatsApp group members","status":"active","dailyVolume":"\u20a612M","txnCount":"2,100"}],
  whatsapp_notification: [{"id":"WNT-001","name":"Credit Alert Template","category":"Template","description":"Transaction credit notification \u2014 HSM approved","status":"approved","language":"en","deliveryRate":"99.5%"},{"id":"WNT-002","name":"Debit Alert Template","category":"Template","description":"Transaction debit notification \u2014 HSM approved","status":"approved","language":"en","deliveryRate":"99.4%"},{"id":"WNT-003","name":"OTP Template","category":"Template","description":"One-time password delivery \u2014 15s expiry","status":"approved","language":"en","deliveryRate":"99.8%"},{"id":"WNT-004","name":"Statement Template","category":"Template","description":"Monthly statement delivery with PDF attachment","status":"approved","language":"en","deliveryRate":"98.9%"}],
  whatsapp_document_service: [{"id":"WDS-001","name":"Account Statement","category":"Document","description":"PDF account statement generation and delivery","status":"active","format":"PDF","avgSize":"245KB"},{"id":"WDS-002","name":"KYC Document Upload","category":"Document","description":"ID card, utility bill, passport photo upload","status":"active","format":"JPEG/PDF","avgSize":"1.2MB"},{"id":"WDS-003","name":"Loan Agreement","category":"Document","description":"Digital loan agreement with e-signature","status":"active","format":"PDF","avgSize":"180KB"},{"id":"WDS-004","name":"Tax Certificate","category":"Document","description":"Withholding tax certificate (WHT) delivery","status":"active","format":"PDF","avgSize":"95KB"}],
  ussd_banking_gateway: [{"id":"USG-001","name":"*737# Main Menu","category":"USSD","description":"Main USSD banking shortcode \u2014 all services","status":"active","dailySessions":"450,000","shortCode":"*737#","operator":"all"},{"id":"USG-002","name":"*737*1# Balance","category":"USSD","description":"Quick balance check \u2014 2-step flow","status":"active","dailySessions":"180,000","shortCode":"*737*1#","operator":"all"},{"id":"USG-003","name":"*737*2# Transfer","category":"USSD","description":"Fund transfer \u2014 account number + amount + PIN","status":"active","dailySessions":"120,000","shortCode":"*737*2#","operator":"all"},{"id":"USG-004","name":"*737*3# Airtime","category":"USSD","description":"Airtime top-up \u2014 self and third party","status":"active","dailySessions":"95,000","shortCode":"*737*3#","operator":"all"}],
  ussd_transaction_engine: [{"id":"UTE-001","name":"Session Manager","category":"Engine","description":"USSD session state machine \u2014 180s timeout, 160-char screens","status":"active","activeSessions":"12,400","maxConcurrent":"50,000"},{"id":"UTE-002","name":"PIN Validator","category":"Engine","description":"4-digit transaction PIN validation with 3-attempt lockout","status":"active","validations":"320,000/day","lockouts":"450/day"},{"id":"UTE-003","name":"Response Formatter","category":"Engine","description":"160-character screen formatter with menu pagination","status":"active","screens":"45 templates","languages":5},{"id":"UTE-004","name":"Timeout Handler","category":"Engine","description":"Session timeout and graceful cleanup \u2014 auto-reversal","status":"active","timeouts":"8,200/day","reversals":"120/day"}],
  ussd_multilingual: [{"id":"UML-001","name":"English (en)","category":"Language","description":"English USSD menu translations \u2014 45 screens","status":"active","screens":45,"completion":"100%"},{"id":"UML-002","name":"Hausa (ha)","category":"Language","description":"Hausa USSD menu translations \u2014 45 screens","status":"active","screens":45,"completion":"100%"},{"id":"UML-003","name":"Yoruba (yo)","category":"Language","description":"Yoruba USSD menu translations \u2014 45 screens","status":"active","screens":45,"completion":"100%"},{"id":"UML-004","name":"Igbo (ig)","category":"Language","description":"Igbo USSD menu translations \u2014 45 screens","status":"active","screens":45,"completion":"100%"},{"id":"UML-005","name":"Pidgin (pcm)","category":"Language","description":"Nigerian Pidgin USSD translations \u2014 45 screens","status":"active","screens":45,"completion":"98%"}],
  ussd_sim_toolkit: [{"id":"STK-001","name":"MTN STK Push","category":"STK","description":"MTN SIM Toolkit push alerts \u2014 balance + debit/credit","status":"active","operator":"MTN","subscribers":"2.4M"},{"id":"STK-002","name":"Glo STK Push","category":"STK","description":"Glo SIM Toolkit push alerts","status":"active","operator":"Glo","subscribers":"890K"},{"id":"STK-003","name":"Airtel STK Push","category":"STK","description":"Airtel SIM Toolkit push alerts","status":"active","operator":"Airtel","subscribers":"1.2M"},{"id":"STK-004","name":"9mobile STK Push","category":"STK","description":"9mobile SIM Toolkit push alerts","status":"active","operator":"9mobile","subscribers":"320K"}],
  sms_banking_gateway: [{"id":"SMG-001","name":"BAL Keyword","category":"SMS","description":"Text BAL to 54000 \u2014 returns account balance","status":"active","keyword":"BAL","dailyVolume":"85,000","shortCode":"54000"},{"id":"SMG-002","name":"TRF Keyword","category":"SMS","description":"Text TRF amount account# to 54000 \u2014 initiates transfer","status":"active","keyword":"TRF","dailyVolume":"32,000","shortCode":"54000"},{"id":"SMG-003","name":"STMT Keyword","category":"SMS","description":"Text STMT to 54000 \u2014 mini statement last 5 txns","status":"active","keyword":"STMT","dailyVolume":"28,000","shortCode":"54000"},{"id":"SMG-004","name":"STOP Keyword","category":"SMS","description":"Text STOP to 54000 \u2014 block card immediately","status":"active","keyword":"STOP","dailyVolume":"450","shortCode":"54000"}],
  sms_otp_service: [{"id":"OTP-001","name":"Transaction OTP","category":"OTP","description":"6-digit OTP for transactions \u2014 5 min expiry, MTN priority route","status":"active","deliveryRate":"99.6%","avgDelivery":"3.2s","expiry":"5min"},{"id":"OTP-002","name":"Login OTP","category":"OTP","description":"6-digit OTP for 2FA login \u2014 10 min expiry","status":"active","deliveryRate":"99.4%","avgDelivery":"3.5s","expiry":"10min"},{"id":"OTP-003","name":"Card PIN OTP","category":"OTP","description":"4-digit OTP for card PIN reset \u2014 3 min expiry","status":"active","deliveryRate":"99.7%","avgDelivery":"2.8s","expiry":"3min"},{"id":"OTP-004","name":"Registration OTP","category":"OTP","description":"6-digit OTP for new account registration","status":"active","deliveryRate":"99.3%","avgDelivery":"4.1s","expiry":"15min"}],
  sms_alert_notification: [{"id":"SAN-001","name":"Credit Alert","category":"Alert","description":"SMS credit notification \u2014 \u20a60.00 threshold","status":"active","template":"CR: {amount} from {sender}. Bal: {balance}","dailyVolume":"420,000"},{"id":"SAN-002","name":"Debit Alert","category":"Alert","description":"SMS debit notification \u2014 \u20a60.00 threshold","status":"active","template":"DR: {amount} to {recipient}. Bal: {balance}","dailyVolume":"380,000"},{"id":"SAN-003","name":"Fraud Alert","category":"Alert","description":"Suspicious transaction alert \u2014 immediate delivery","status":"active","template":"URGENT: Suspicious txn {amount}. Call 0800-54-BANK","dailyVolume":"1,200"},{"id":"SAN-004","name":"Loan Due Alert","category":"Alert","description":"Loan repayment reminder \u2014 3 days before due","status":"active","template":"Reminder: \u20a6{amount} due on {date}. Dial *737*5#","dailyVolume":"15,000"}],
};

export function registerChannelBankingRoutes(app: Express): void {
  for (const svc of CHANNEL_SERVICES) {
    const listUrl = `http://localhost:${svc.port}/v1/${svc.topic}/list`;
    const healthUrl = `http://localhost:${svc.port}/healthz`;

    app.get(`/api/channel-banking/${svc.path}/list`, async (_req, res) => {
      try {
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 3000);
        const resp = await fetch(listUrl, { signal: controller.signal as never });
        clearTimeout(timeout);
        const data = await resp.json();
        res.json(data);
      } catch {
        const items = SEED_FALLBACK[svc.topic] || [];
        res.json({ items, total: items.length, service: svc.name, fallback: true });
      }
    });

    app.get(`/api/channel-banking/${svc.path}/healthz`, async (_req, res) => {
      try {
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 3000);
        const resp = await fetch(healthUrl, { signal: controller.signal as never });
        clearTimeout(timeout);
        const data = await resp.json();
        res.json(data);
      } catch {
        res.json({ status: "unavailable", service: svc.name, fallback: true });
      }
    });
  }
}
