replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54link-dev-ai-graph-search
  pullPolicy: IfNotPresent
  tag: "0.0.1"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54link
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9107
    - port: 9108
    - port: 9109
    - port: 9110
    - port: 9111
    - port: 9112
    - port: 9113
    - port: 9114
    - port: 9115
    - port: 9116
    - port: 9117
    - port: 9118
    - port: 9119
    - port: 9120
    - port: 9121
    - port: 9122
    - port: 9123
    - port: 9124
    - port: 9125
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    ephemeral-storage: 2Gi
    cpu: 500m
    memory: 1Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: ai-graph-search
  appPort: 9109
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  APP_PORT: "9107"
  PORT_BASE: "9107"
  SERVICE_GROUP: ai-graph-search
  SERVICES: "cocoindex-pipeline-py,epr-kgqa-engine-py,epr-kgqa-go,epr-kgqa-py,epr-kgqa-rs,falkordb-coa-go,falkordb-coa-py,falkordb-coa-rs,falkordb-graph-engine-rs,falkordb-graph-rs,kgqa-reasoning-engine-py,langchain-agent-go,neo4j-coa-graph-go,neo4j-coa-graph-rs,neo4j-knowledge-graph-go,ollama-inference-go,qdrant-financial-search-go,qdrant-vector-store-rs,search-service"
