apiVersion: v1
kind: Service
metadata:
  name: {{ include "safe-deposit-go.fullname" . }}
  labels:
    {{- include "safe-deposit-go.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
      name: port-{{ .port }}
    {{- end }}
  selector:
    {{- include "safe-deposit-go.selectorLabels" . | nindent 4 }}
