{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "safe-deposit-go.serviceAccountName" . }}
  labels:
    {{- include "safe-deposit-go.labels" . | nindent 4 }}
{{- end }}
