apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "54bank.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "54bank.name" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "54bank.name" . }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/api/metrics/prometheus"
      labels:
        app.kubernetes.io/name: {{ include "54bank.name" . }}
    spec:
      serviceAccountName: {{ include "54bank.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: ENABLE_AUTH
              value: {{ .Values.env.ENABLE_AUTH | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.existingSecret }}
                  key: url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.existingSecret }}
                  key: url
            - name: KAFKA_BROKERS
              value: {{ .Values.kafka.brokers | quote }}
            - name: KEYCLOAK_URL
              value: {{ .Values.keycloak.url | quote }}
          livenessProbe:
            httpGet:
              path: /api/live
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
