apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: 54bank-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secrets.externalSecretsStore }}
    kind: ClusterSecretStore
  target:
    name: 54bank-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.secrets.secretKeys }}
    - secretKey: {{ . }}
      remoteRef:
        key: 54bank/{{ $.Values.global.environment }}/{{ . }}
    {{- end }}
