replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54link-dev-esusu-service
  pullPolicy: IfNotPresent
  tag: "0.0.1"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54link
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8089
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    ephemeral-storage: 1Gi
    cpu: 300m
    memory: 512Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: esusu-service
  appPort: 8089
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  APP_PORT: "8089"
  PORT: "8089"
  PORT_BASE: "8089"
  SERVICE_GROUP: esusu-service
  SERVICES: "esusu-service"
