FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o banking-domain-integration .

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/banking-domain-integration .
EXPOSE 8096
CMD ["./banking-domain-integration"]
