{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fee-management-go.serviceAccountName" . }}
  labels:
    {{- include "fee-management-go.labels" . | nindent 4 }}
{{- end }}
