openapi: "3.0.0"
info:
  title: "orchestrator-service"
  version: "1.0.0"
  description: "54link orchestrator service"
tags:
  - name: ""
    description: ""

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
