name: Build and Deploy Interest Rate Engine Service

on:
  push:
    branches:
      - main
      - development
    paths:
      - 'services/interest-rate-engine-go/**'
      - 'infrastructure/charts/interest-rate-engine-go/**'
      - 'infrastructure/apisix-resources/routes/interest-rate-engine-go.yaml'
      - '.github/workflows/interest-rate-engine-go.yaml'

env:
  IMAGE: registry.digitalocean.com/talentgraph-auth/54link-dev-interest-rate-engine-go
  TAG: "0.0.1"
  CHART: infrastructure/charts/interest-rate-engine-go
  RELEASE: interest-rate-engine-go
  NAMESPACE: 54link-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: docker
          password: ${{ secrets.DO_API_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/interest-rate-engine-go
          file: ./services/interest-rate-engine-go/Dockerfile
          push: true
          tags: ${{ env.IMAGE }}:${{ env.TAG }}

