name: Build Tenant Web App

on:
  push:
    branches:
      - main
      - development
    paths:
      - 'uis/admin/tenant_admin/**'
      - '.github/workflows/tenant-web-app.yaml'

env:
  TAG: "0.0.6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: docker
          password: ${{ secrets.DO_API_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./uis/admin/tenant_admin
          file: ./uis/admin/tenant_admin/Dockerfile
          push: true
          tags: registry.digitalocean.com/talentgraph-auth/54link-dev-tenant-web-app:${{ env.TAG }}
